"""add_oauth2_client_credentials

Revision ID: 1236f759fffe
Revises: hh22ee334455
Create Date: 2026-08-01 17:02:51.904611

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1236f759fffe'
down_revision: Union[str, None] = 'hh22ee334455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic_postgresql_enum import TableReference

def upgrade() -> None:
    # We must also keep the autogenerated index
    op.create_index('idx_queued_runs_callback', 'queued_runs', ['campaign_id', 'scheduled_for'], unique=False, postgresql_where=sa.text("state = 'queued' AND retry_reason = 'user_requested_callback'"))

    op.sync_enum_values(
        enum_schema="public",
        enum_name="webhook_credential_type",
        new_values=[
            "none",
            "api_key",
            "bearer_token",
            "basic_auth",
            "custom_header",
            "oauth2_client_credentials",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="external_credentials",
                column_name="credential_type",
            )
        ],
        enum_values_to_rename=[],
    )

def downgrade() -> None:
    op.drop_index('idx_queued_runs_callback', table_name='queued_runs', postgresql_where=sa.text("state = 'queued' AND retry_reason = 'user_requested_callback'"))

    op.sync_enum_values(
        enum_schema="public",
        enum_name="webhook_credential_type",
        new_values=[
            "none",
            "api_key",
            "bearer_token",
            "basic_auth",
            "custom_header",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="external_credentials",
                column_name="credential_type",
            )
        ],
        enum_values_to_rename=[],
    )
