apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: zoren-voice-prod
  labels:
    app: zoren-voice-minio
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 20Gi
