apiVersion: v1
kind: Service
metadata:
  name: voice-redis
  namespace: zoren-voice-prod
  labels:
    app: zoren-voice-redis
    env: prod
spec:
  type: ClusterIP
  selector:
    app: zoren-voice-redis
    env: prod
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
