# generated by datamodel-codegen:
#   filename:  dograh-openapi-XXXXXX.json.4udL1BKKri
#   timestamp: 2026-10-06T00:02:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AmbientNoiseConfigurationDefaults(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    enabled: Annotated[bool | None, Field(title='Enabled')] = False
    volume: Annotated[float | None, Field(title='Volume')] = 0.3


class CalculatorToolDefinition(BaseModel):
    """
    Tool definition for Calculator tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['calculator'], Field(title='Type')]
    """
    Tool type.
    """


class CallDispositionCodes(BaseModel):
    disposition_codes: Annotated[list[str] | None, Field(title='Disposition Codes')] = (
        []
    )


class CallDispositionOption(BaseModel):
    """
    One business outcome the terminal classifier may select.
    """

    code: Annotated[
        str,
        Field(
            max_length=64,
            min_length=1,
            pattern='^[A-Za-z][A-Za-z0-9_-]*$',
            title='Code',
        ),
    ]
    """
    Stable code recorded when this outcome is selected.
    """
    description: Annotated[
        str, Field(max_length=1000, min_length=1, title='Description')
    ]
    """
    Business criteria for selecting this disposition.
    """


class CallType(Enum):
    inbound = 'inbound'
    outbound = 'outbound'


class CampaignLogEntryResponse(BaseModel):
    """
    A single timestamped entry from the campaign's append-only log.

    Surfaced in the UI so operators can see why a campaign moved to
    paused / failed without digging through server logs.
    """

    ts: Annotated[str, Field(title='Ts')]
    level: Annotated[str, Field(title='Level')]
    event: Annotated[str, Field(title='Event')]
    message: Annotated[str, Field(title='Message')]
    details: Annotated[dict[str, Any] | None, Field(title='Details')] = None


class CampaignProgressResponse(BaseModel):
    campaign_id: Annotated[int, Field(title='Campaign Id')]
    state: Annotated[str, Field(title='State')]
    total_rows: Annotated[int, Field(title='Total Rows')]
    processed_rows: Annotated[int, Field(title='Processed Rows')]
    failed_calls: Annotated[int, Field(title='Failed Calls')]
    progress_percentage: Annotated[float, Field(title='Progress Percentage')]
    source_sync: Annotated[dict[str, Any], Field(title='Source Sync')]
    rate_limit: Annotated[int, Field(title='Rate Limit')]
    started_at: Annotated[AwareDatetime | None, Field(title='Started At')]
    completed_at: Annotated[AwareDatetime | None, Field(title='Completed At')]


class CircuitBreakerConfigRequest(BaseModel):
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    failure_threshold: Annotated[
        float | None, Field(ge=0.0, le=1.0, title='Failure Threshold')
    ] = 0.5
    window_seconds: Annotated[
        int | None, Field(ge=30, le=600, title='Window Seconds')
    ] = 120
    min_calls_in_window: Annotated[
        int | None, Field(ge=1, le=100, title='Min Calls In Window')
    ] = 5


class CircuitBreakerConfigResponse(BaseModel):
    enabled: Annotated[bool | None, Field(title='Enabled')] = False
    failure_threshold: Annotated[float | None, Field(title='Failure Threshold')] = 0.5
    window_seconds: Annotated[int | None, Field(title='Window Seconds')] = 120
    min_calls_in_window: Annotated[int | None, Field(title='Min Calls In Window')] = 5


class FallbackDestination(RootModel[str]):
    root: Annotated[str, Field(max_length=255, title='Fallback Destination')]
    """
    Optional provider-native destination or context template used when no rule matched.
    """


class ContextDestinationRoute(BaseModel):
    """
    Map one context value to a transfer destination.
    """

    context_value: Annotated[
        str, Field(max_length=255, min_length=1, title='Context Value')
    ]
    """
    Context value that selects this destination.
    """
    destination: Annotated[
        str, Field(max_length=255, min_length=1, title='Destination')
    ]
    """
    VICIdial in-group, SIP endpoint, E.164 phone number, or context template used when this route matches.
    """


class ContextDestinationRule(BaseModel):
    """
    One context lookup with its value-to-destination routes.
    """

    context_path: Annotated[
        str, Field(max_length=255, min_length=1, title='Context Path')
    ]
    """
    Context path used for routing. An unprefixed path checks gathered context first, then initial context; use initial_context.* or gathered_context.* to select one explicitly.
    """
    routes: Annotated[
        list[ContextDestinationRoute],
        Field(max_length=100, min_length=1, title='Routes'),
    ]


class WorkflowId(RootModel[int]):
    root: Annotated[int, Field(gt=0, title='Workflow Id')]


class MaxConcurrency(RootModel[int]):
    root: Annotated[int, Field(ge=1, title='Max Concurrency')]


class CreateFolderRequest(BaseModel):
    name: Annotated[str, Field(max_length=100, min_length=1, title='Name')]


class Category(Enum):
    """
    Tool category. Must match definition.type.
    """

    http_api = 'http_api'
    end_call = 'end_call'
    transfer_call = 'transfer_call'
    transfer_agent = 'transfer_agent'
    calculator = 'calculator'
    native = 'native'
    integration = 'integration'
    mcp = 'mcp'


class Icon(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Icon')] = 'globe'
    """
    Lucide icon identifier.
    """


class IconColor(RootModel[str]):
    root: Annotated[str, Field(max_length=7, title='Icon Color')] = '#3B82F6'
    """
    Hex color for the tool icon.
    """


class CreateWorkflowRequest(BaseModel):
    name: Annotated[str, Field(title='Name')]
    workflow_definition: Annotated[dict[str, Any], Field(title='Workflow Definition')]


class CreatedByResponse(BaseModel):
    """
    Response schema for the user who created a tool.
    """

    id: Annotated[int, Field(title='Id')]
    provider_id: Annotated[str, Field(title='Provider Id')]


class CredentialResponse(BaseModel):
    """
    Response schema for a webhook credential (never includes sensitive data).
    """

    uuid: Annotated[str, Field(title='Uuid')]
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')]
    credential_type: Annotated[str, Field(title='Credential Type')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime | None, Field(title='Updated At')]


class DisplayOptions(BaseModel):
    """
    Conditional visibility rules.

    `show` keys are AND-combined: this property is visible only when EVERY
    referenced field's value matches one of the listed values.

    `hide` keys are OR-combined: this property is hidden when ANY referenced
    field's value matches one of the listed values.

    Example:
        DisplayOptions(show={"extraction_enabled": [True]})
        DisplayOptions(show={"greeting_type": ["audio"]})
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    show: Annotated[dict[str, list[Any]] | None, Field(title='Show')] = None
    hide: Annotated[dict[str, list[Any]] | None, Field(title='Hide')] = None


class DocumentResponseSchema(BaseModel):
    """
    Response schema for document metadata.
    """

    id: Annotated[int, Field(title='Id')]
    document_uuid: Annotated[str, Field(title='Document Uuid')]
    filename: Annotated[str, Field(title='Filename')]
    file_size_bytes: Annotated[int, Field(title='File Size Bytes')]
    file_hash: Annotated[str, Field(title='File Hash')]
    mime_type: Annotated[str, Field(title='Mime Type')]
    processing_status: Annotated[str, Field(title='Processing Status')]
    processing_error: Annotated[str | None, Field(title='Processing Error')] = None
    total_chunks: Annotated[int, Field(title='Total Chunks')]
    retrieval_mode: Annotated[str | None, Field(title='Retrieval Mode')] = 'chunked'
    custom_metadata: Annotated[dict[str, Any], Field(title='Custom Metadata')]
    docling_metadata: Annotated[dict[str, Any], Field(title='Docling Metadata')]
    source_url: Annotated[str | None, Field(title='Source Url')] = None
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime, Field(title='Updated At')]
    organization_id: Annotated[int, Field(title='Organization Id')]
    created_by: Annotated[int, Field(title='Created By')]
    is_active: Annotated[bool, Field(title='Is Active')]
    has_live_content: Annotated[bool | None, Field(title='Has Live Content')] = False
    """
    Whether agents can currently retrieve this document's content. Stays true while an edited document is re-indexed or after its re-index fails, because the previous version keeps serving until a new one succeeds.
    """


class MessageType(Enum):
    """
    Type of goodbye message.
    """

    none = 'none'
    custom = 'custom'
    audio = 'audio'


class EndCallConfig(BaseModel):
    """
    Configuration for End Call tools.
    """

    messageType: Annotated[MessageType | None, Field(title='Messagetype')] = 'none'
    """
    Type of goodbye message.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before ending the call.
    """
    audioRecordingId: Annotated[str | None, Field(title='Audiorecordingid')] = None
    """
    Recording ID for audio goodbye message.
    """
    endCallReason: Annotated[bool | None, Field(title='Endcallreason')] = False
    """
    When enabled, the model must provide a reason for ending the call. The reason is set as call disposition and added to call tags.
    """
    endCallReasonDescription: Annotated[
        str | None, Field(title='Endcallreasondescription')
    ] = None
    """
    Description shown to the model for the reason parameter. Used only when endCallReason is enabled.
    """


class EndCallToolDefinition(BaseModel):
    """
    Tool definition for End Call tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['end_call'], Field(title='Type')]
    """
    Tool type.
    """
    config: EndCallConfig
    """
    End Call configuration.
    """


class ErrorCondition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Annotated[Literal['error'], Field(title='Type')] = 'error'


class ExternalPBXFieldMapping(BaseModel):
    """
    Map one gathered-context value to a provider-native field.
    """

    context_path: Annotated[
        str, Field(max_length=255, min_length=1, title='Context Path')
    ]
    destination_field: Annotated[
        str, Field(pattern='^[A-Za-z][A-Za-z0-9_]{0,63}$', title='Destination Field')
    ]


class FolderResponse(BaseModel):
    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]


class GraphConstraints(BaseModel):
    """
    Per-node-type graph rules. WorkflowGraph enforces these at validation.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    min_incoming: Annotated[int | None, Field(title='Min Incoming')] = None
    max_incoming: Annotated[int | None, Field(title='Max Incoming')] = None
    min_outgoing: Annotated[int | None, Field(title='Min Outgoing')] = None
    max_outgoing: Annotated[int | None, Field(title='Max Outgoing')] = None
    min_instances: Annotated[int | None, Field(title='Min Instances')] = None
    max_instances: Annotated[int | None, Field(title='Max Instances')] = None


class Method(Enum):
    """
    HTTP method to use for the request.
    """

    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'


class TimeoutMs(RootModel[int]):
    root: Annotated[int, Field(ge=1, title='Timeout Ms')] = 5000
    """
    Request timeout in milliseconds.
    """


class CustomMessageType(Enum):
    """
    Type of custom message.
    """

    text = 'text'
    audio = 'audio'


class BodyFormat(Enum):
    """
    Encoding of the POST, PUT, and PATCH request body: 'json' sends application/json, 'form' sends application/x-www-form-urlencoded.
    """

    json = 'json'
    form = 'form'


class InitiateCallRequest(BaseModel):
    workflow_id: Annotated[int, Field(title='Workflow Id')]
    workflow_run_id: Annotated[int | None, Field(title='Workflow Run Id')] = None
    phone_number: Annotated[str | None, Field(title='Phone Number')] = None
    telephony_configuration_id: Annotated[
        int | None, Field(title='Telephony Configuration Id')
    ] = None
    from_phone_number_id: Annotated[int | None, Field(title='From Phone Number Id')] = (
        None
    )


class ItemKind(Enum):
    node = 'node'
    edge = 'edge'
    workflow = 'workflow'


class McpToolConfig(BaseModel):
    """
    Configuration for a customer MCP server tool definition.
    """

    transport: Annotated[Literal['streamable_http'], Field(title='Transport')] = (
        'streamable_http'
    )
    """
    MCP transport protocol.
    """
    url: Annotated[str, Field(title='Url')]
    """
    MCP server URL. Must use http:// or https://.
    """
    credential_uuid: Annotated[str | None, Field(title='Credential Uuid')] = None
    """
    Reference to an external credential for MCP server auth.
    """
    tools_filter: Annotated[list[str] | None, Field(title='Tools Filter')] = None
    """
    Allowlist of MCP tool names to expose. Empty exposes all tools.
    """
    timeout_secs: Annotated[int | None, Field(ge=0, title='Timeout Secs')] = 30
    """
    Connection timeout in seconds.
    """
    sse_read_timeout_secs: Annotated[
        int | None, Field(ge=0, title='Sse Read Timeout Secs')
    ] = 300
    """
    SSE read timeout in seconds.
    """
    discovered_tools: Annotated[
        list[dict[str, Any]] | None, Field(title='Discovered Tools')
    ] = None
    """
    Server-managed cache of the MCP server's tool catalog [{name, description}]. Populated best-effort by the backend.
    """


class McpToolDefinition(BaseModel):
    """
    Persisted MCP tool definition.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['mcp'], Field(title='Type')]
    """
    Tool type.
    """
    config: McpToolConfig
    """
    MCP server configuration.
    """


class Mode(Enum):
    pipeline = 'pipeline'
    realtime = 'realtime'


class NoOutputCondition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Annotated[Literal['no_output'], Field(title='Type')] = 'no_output'
    after_ms: Annotated[int | None, Field(ge=100, le=10000, title='After Ms')] = 1500


class NodeCategory(Enum):
    """
    Drives grouping in the AddNodePanel UI.
    """

    call_node = 'call_node'
    global_node = 'global_node'
    trigger = 'trigger'
    integration = 'integration'


class NodeExample(BaseModel):
    """
    A worked example LLMs can pattern-match. Keep small and realistic.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')] = None
    data: Annotated[dict[str, Any], Field(title='Data')]


class NumberInputOptions(BaseModel):
    """
    Renderer hints for numeric inputs.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    fractional: Annotated[bool | None, Field(title='Fractional')] = False
    """
    Allow arbitrary fractional values via step='any'.
    """


class Type(Enum):
    """
    JSON type for the resolved value.
    """

    string = 'string'
    number = 'number'
    boolean = 'boolean'
    object = 'object'
    array = 'array'


class PresetToolParameter(BaseModel):
    """
    A parameter injected by Dograh at runtime.
    """

    name: Annotated[str, Field(title='Name')]
    """
    Parameter name used as a key in the request body.
    """
    type: Annotated[Type, Field(title='Type')]
    """
    JSON type for the resolved value.
    """
    value_template: Annotated[str, Field(title='Value Template')]
    """
    Fixed value or template, e.g. {{initial_context.phone_number}}.
    """
    required: Annotated[bool | None, Field(title='Required')] = True
    """
    Whether the parameter must resolve to a non-empty value.
    """


class ColumnSpan(RootModel[int]):
    root: Annotated[int, Field(ge=1, le=12, title='Column Span')]
    """
    Number of columns to occupy in the editor's 12-column grid.
    """


class PropertyLayoutOptions(BaseModel):
    """
    Renderer layout hints for a property in the node editor.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    column_span: Annotated[ColumnSpan | None, Field(title='Column Span')] = None
    """
    Number of columns to occupy in the editor's 12-column grid.
    """


class PropertyOption(BaseModel):
    """
    An option in an `options` or `multi_options` dropdown.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: Annotated[str | int | bool | float, Field(title='Value')]
    label: Annotated[str, Field(title='Label')]
    description: Annotated[str | None, Field(title='Description')] = None


class PropertyRendererOptions(BaseModel):
    """
    Typed renderer metadata for node properties.

    Add new renderer behavior here instead of using free-form property metadata.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    layout: PropertyLayoutOptions | None = None
    number_input: NumberInputOptions | None = None


class PropertyType(Enum):
    """
    Bounded vocabulary of property types the renderer dispatches on.

    Adding a value here requires a matching arm in the frontend
    `<PropertyInput>` switch and (where relevant) the SDK codegen template.
    """

    string = 'string'
    number = 'number'
    boolean = 'boolean'
    options = 'options'
    multi_options = 'multi_options'
    fixed_collection = 'fixed_collection'
    json = 'json'
    tool_refs = 'tool_refs'
    document_refs = 'document_refs'
    recording_ref = 'recording_ref'
    credential_ref = 'credential_ref'
    mention_textarea = 'mention_textarea'
    url = 'url'


class VersionName(RootModel[str]):
    root: Annotated[str, Field(max_length=100, min_length=1, title='Version Name')]


class ChangeDescription(RootModel[str]):
    root: Annotated[
        str, Field(max_length=500, min_length=1, title='Change Description')
    ]


class PublishWorkflowRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version_name: Annotated[VersionName | None, Field(title='Version Name')] = None
    change_description: Annotated[
        ChangeDescription | None, Field(title='Change Description')
    ] = None


class PublishWorkflowResponse(BaseModel):
    """
    Published version, including the release notes stored on publish.
    """

    id: Annotated[int, Field(title='Id')]
    version_number: Annotated[int | None, Field(title='Version Number')]
    status: Annotated[str, Field(title='Status')]
    published_at: Annotated[AwareDatetime | None, Field(title='Published At')]
    version_name: Annotated[str | None, Field(title='Version Name')] = None
    change_description: Annotated[str | None, Field(title='Change Description')] = None


class RecordingResponseSchema(BaseModel):
    """
    Response schema for a single recording.
    """

    id: Annotated[int, Field(title='Id')]
    recording_id: Annotated[str, Field(title='Recording Id')]
    workflow_id: Annotated[int | None, Field(title='Workflow Id')] = None
    organization_id: Annotated[int, Field(title='Organization Id')]
    tts_provider: Annotated[str | None, Field(title='Tts Provider')] = None
    tts_model: Annotated[str | None, Field(title='Tts Model')] = None
    tts_voice_id: Annotated[str | None, Field(title='Tts Voice Id')] = None
    transcript: Annotated[str, Field(title='Transcript')]
    storage_key: Annotated[str, Field(title='Storage Key')]
    storage_backend: Annotated[str, Field(title='Storage Backend')]
    metadata: Annotated[dict[str, Any], Field(title='Metadata')]
    created_by: Annotated[int, Field(title='Created By')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    is_active: Annotated[bool, Field(title='Is Active')]


class RetryConfigRequest(BaseModel):
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    max_retries: Annotated[int | None, Field(ge=0, le=10, title='Max Retries')] = 2
    retry_delay_seconds: Annotated[
        int | None, Field(ge=30, le=3600, title='Retry Delay Seconds')
    ] = 120
    retry_on_busy: Annotated[bool | None, Field(title='Retry On Busy')] = True
    retry_on_no_answer: Annotated[bool | None, Field(title='Retry On No Answer')] = True
    retry_on_voicemail: Annotated[bool | None, Field(title='Retry On Voicemail')] = True


class RetryConfigResponse(BaseModel):
    enabled: Annotated[bool, Field(title='Enabled')]
    max_retries: Annotated[int, Field(title='Max Retries')]
    retry_delay_seconds: Annotated[int, Field(title='Retry Delay Seconds')]
    retry_on_busy: Annotated[bool, Field(title='Retry On Busy')]
    retry_on_no_answer: Annotated[bool, Field(title='Retry On No Answer')]
    retry_on_voicemail: Annotated[bool, Field(title='Retry On Voicemail')]


class ServiceOverride(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    settings: Annotated[dict[str, Any] | None, Field(title='Settings')] = None
    provider_connection_uuid: Annotated[
        UUID | None, Field(title='Provider Connection Uuid')
    ] = None


class ServiceSelection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    settings: Annotated[dict[str, Any] | None, Field(title='Settings')] = None
    provider_connection_uuid: Annotated[UUID, Field(title='Provider Connection Uuid')]


class TimeSlotRequest(BaseModel):
    day_of_week: Annotated[int, Field(ge=0, le=6, title='Day Of Week')]
    start_time: Annotated[str, Field(pattern='^\\d{2}:\\d{2}$', title='Start Time')]
    end_time: Annotated[str, Field(pattern='^\\d{2}:\\d{2}$', title='End Time')]


class TimeSlotResponse(BaseModel):
    day_of_week: Annotated[int, Field(title='Day Of Week')]
    start_time: Annotated[str, Field(title='Start Time')]
    end_time: Annotated[str, Field(title='End Time')]


class Type1(Enum):
    """
    JSON type for the parameter value.
    """

    string = 'string'
    number = 'number'
    boolean = 'boolean'
    object = 'object'
    array = 'array'


class ToolParameter(BaseModel):
    """
    A parameter that the tool accepts from the model at call time.
    """

    name: Annotated[str, Field(title='Name')]
    """
    Parameter name used as a key in the tool request body.
    """
    type: Annotated[Type1, Field(title='Type')]
    """
    JSON type for the parameter value.
    """
    description: Annotated[str, Field(title='Description')]
    """
    Description shown to the model for this parameter.
    """
    required: Annotated[bool | None, Field(title='Required')] = True
    """
    Whether this parameter is required when the tool is called.
    """


class ToolResponse(BaseModel):
    """
    Response schema for a reusable tool.
    """

    id: Annotated[int, Field(title='Id')]
    tool_uuid: Annotated[str, Field(title='Tool Uuid')]
    name: Annotated[str, Field(title='Name')]
    description: Annotated[str | None, Field(title='Description')]
    category: Annotated[str, Field(title='Category')]
    icon: Annotated[str | None, Field(title='Icon')]
    icon_color: Annotated[str | None, Field(title='Icon Color')]
    status: Annotated[str, Field(title='Status')]
    definition: Annotated[dict[str, Any], Field(title='Definition')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    updated_at: Annotated[AwareDatetime | None, Field(title='Updated At')]
    created_by: CreatedByResponse | None = None


class WorkflowDefinitionId(RootModel[int]):
    root: Annotated[int, Field(gt=0, title='Workflow Definition Id')]


class TrafficVariantRequest(BaseModel):
    workflow_id: Annotated[int, Field(gt=0, title='Workflow Id')]
    workflow_definition_id: Annotated[
        WorkflowDefinitionId | None, Field(title='Workflow Definition Id')
    ] = None
    weight: Annotated[int, Field(ge=1, le=100, title='Weight')]


class TrafficVariantResponse(BaseModel):
    workflow_id: Annotated[int, Field(gt=0, title='Workflow Id')]
    workflow_definition_id: Annotated[
        WorkflowDefinitionId | None, Field(title='Workflow Definition Id')
    ] = None
    weight: Annotated[int, Field(ge=1, le=100, title='Weight')]
    id: Annotated[str, Field(title='Id')]
    workflow_name: Annotated[str, Field(title='Workflow Name')]
    version_number: Annotated[int | None, Field(title='Version Number')] = None


class TransferAgentConfig(BaseModel):
    """
    Configuration for Transfer Agent tools.

    One tool, one destination. An agent that can hand the caller to several
    places gets several of these tools, and the model chooses between them the
    way it chooses between any other tools -- by their names and descriptions.
    That keeps the routing decision in the one place the model already reasons
    about, and leaves nothing to configure here but where the call goes.

    Most of how a handoff sounds is fixed: the caller hears a ringer while the
    next agent is prepared. The handover line is configurable because it is
    caller-facing and Dograh runs in more than one language, and so is whether
    the next agent opens with its greeting, because an agent that greets
    callers on its own number should not re-introduce itself mid-conversation.
    """

    workflow_id: Annotated[int, Field(title='Workflow Id')]
    """
    Id of the Dograh agent to transfer to. Must be in the same organization, and must not be a speech-to-speech agent.
    """
    message: Annotated[str | None, Field(max_length=500, title='Message')] = (
        'Let me connect you with the right person. One moment please.'
    )
    """
    Spoken by the current agent, in its own voice, before the caller is handed over. Supports template variables. Leave empty to hand over without saying anything.
    """
    play_greeting: Annotated[bool | None, Field(title='Play Greeting')] = True
    """
    Whether the destination agent opens with its Start Call greeting. When false, it skips the greeting and opens with a reply generated from the handover note, continuing the conversation instead of introducing itself.
    """


class TransferAgentToolDefinition(BaseModel):
    """
    Tool definition for Transfer Agent tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['transfer_agent'], Field(title='Type')]
    """
    Tool type.
    """
    config: TransferAgentConfig
    """
    Transfer Agent configuration.
    """


class DestinationSource(Enum):
    """
    Whether the destination is static/template, resolved by HTTP, or selected by ordered gathered/initial-context mapping rules.
    """

    static = 'static'
    dynamic = 'dynamic'
    context_mapping = 'context_mapping'


class MessageType1(Enum):
    """
    Type of message to play before transfer.
    """

    none = 'none'
    custom = 'custom'
    audio = 'audio'


class CallDisposition(RootModel[str]):
    root: Annotated[str, Field(max_length=64, title='Call Disposition')]
    """
    Optional disposition to record after a successful transfer. When omitted, Dograh records its provider-specific transfer default.
    """


class Name(RootModel[str]):
    root: Annotated[str, Field(max_length=255, title='Name')]


class Icon1(RootModel[str]):
    root: Annotated[str, Field(max_length=50, title='Icon')]


class IconColor1(RootModel[str]):
    root: Annotated[str, Field(max_length=7, title='Icon Color')]


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]
    input: Annotated[Any | None, Field(title='Input')] = None
    ctx: Annotated[dict[str, Any] | None, Field(title='Context')] = None


class TurnStartStrategy(Enum):
    default = 'default'
    min_words = 'min_words'


class TurnStopStrategy(Enum):
    transcription = 'transcription'
    turn_analyzer = 'turn_analyzer'


class ExternalPbxLeadHeader(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Za-z][A-Za-z0-9_]{0,63}$')]


class WorkflowError(BaseModel):
    kind: ItemKind
    id: Annotated[str | None, Field(title='Id')]
    field: Annotated[str | None, Field(title='Field')]
    message: Annotated[str, Field(title='Message')]


class WorkflowListResponse(BaseModel):
    """
    Lightweight response for workflow listings (excludes large fields).
    """

    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    status: Annotated[str, Field(title='Status')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    total_runs: Annotated[int, Field(title='Total Runs')]
    folder_id: Annotated[int | None, Field(title='Folder Id')] = None
    workflow_uuid: Annotated[str | None, Field(title='Workflow Uuid')] = None


class WorkflowResponse(BaseModel):
    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    status: Annotated[str, Field(title='Status')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    workflow_definition: Annotated[dict[str, Any], Field(title='Workflow Definition')]
    current_definition_id: Annotated[int | None, Field(title='Current Definition Id')]
    template_context_variables: Annotated[
        dict[str, Any] | None, Field(title='Template Context Variables')
    ] = None
    call_disposition_codes: CallDispositionCodes | None = None
    total_runs: Annotated[int | None, Field(title='Total Runs')] = None
    workflow_configurations: Annotated[
        dict[str, Any] | None, Field(title='Workflow Configurations')
    ] = None
    version_number: Annotated[int | None, Field(title='Version Number')] = None
    version_status: Annotated[str | None, Field(title='Version Status')] = None
    workflow_uuid: Annotated[str | None, Field(title='Workflow Uuid')] = None


class WorkflowRunResponseSchema(BaseModel):
    id: Annotated[int, Field(title='Id')]
    workflow_id: Annotated[int, Field(title='Workflow Id')]
    workflow_name: Annotated[str | None, Field(title='Workflow Name')] = None
    version_number: Annotated[int | None, Field(title='Version Number')] = None
    name: Annotated[str, Field(title='Name')]
    mode: Annotated[str, Field(title='Mode')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    is_completed: Annotated[bool, Field(title='Is Completed')]
    transcript_url: Annotated[str | None, Field(title='Transcript Url')]
    recording_url: Annotated[str | None, Field(title='Recording Url')]
    user_recording_url: Annotated[str | None, Field(title='User Recording Url')] = None
    bot_recording_url: Annotated[str | None, Field(title='Bot Recording Url')] = None
    transcript_public_url: Annotated[
        str | None, Field(title='Transcript Public Url')
    ] = None
    recording_public_url: Annotated[str | None, Field(title='Recording Public Url')] = (
        None
    )
    user_recording_public_url: Annotated[
        str | None, Field(title='User Recording Public Url')
    ] = None
    bot_recording_public_url: Annotated[
        str | None, Field(title='Bot Recording Public Url')
    ] = None
    public_access_token: Annotated[str | None, Field(title='Public Access Token')] = (
        None
    )
    cost_info: Annotated[dict[str, Any] | None, Field(title='Cost Info')]
    usage_info: Annotated[dict[str, Any] | None, Field(title='Usage Info')] = None
    definition_id: Annotated[int | None, Field(title='Definition Id')]
    initial_context: Annotated[
        dict[str, Any] | None, Field(title='Initial Context')
    ] = None
    gathered_context: Annotated[
        dict[str, Any] | None, Field(title='Gathered Context')
    ] = None
    call_type: CallType
    logs: Annotated[dict[str, Any] | None, Field(title='Logs')] = None
    annotations: Annotated[dict[str, Any] | None, Field(title='Annotations')] = None


class WorkflowRunsResponse(BaseModel):
    runs: Annotated[list[WorkflowRunResponseSchema], Field(title='Runs')]
    total_count: Annotated[int, Field(title='Total Count')]
    page: Annotated[int, Field(title='Page')]
    limit: Annotated[int, Field(title='Limit')]
    total_pages: Annotated[int, Field(title='Total Pages')]
    applied_filters: Annotated[
        list[dict[str, Any]] | None, Field(title='Applied Filters')
    ] = None


class ContextDestinationMappingConfig(BaseModel):
    """
    Resolve a transfer destination from gathered or initial context.

    Rules are evaluated in order. The first rule whose context value matches
    one of its routes wins; ``fallback_destination`` applies only when no rule
    matched. Destinations may be provider-native values or context templates.
    """

    rules: Annotated[list[ContextDestinationRule] | None, Field(title='Rules')] = None
    """
    Ordered routing rules evaluated top to bottom; first match wins.
    """
    context_path: Annotated[str | None, Field(title='Context Path')] = None
    """
    Deprecated single-rule context path. Use rules instead; accepted for backward compatibility.
    """
    routes: Annotated[list[ContextDestinationRoute] | None, Field(title='Routes')] = (
        None
    )
    """
    Deprecated single-rule routes. Use rules instead; accepted for backward compatibility.
    """
    fallback_destination: Annotated[
        FallbackDestination | None, Field(title='Fallback Destination')
    ] = None
    """
    Optional provider-native destination or context template used when no rule matched.
    """


class DocumentListResponseSchema(BaseModel):
    """
    Response schema for list of documents.
    """

    documents: Annotated[list[DocumentResponseSchema], Field(title='Documents')]
    total: Annotated[int, Field(title='Total')]
    limit: Annotated[int, Field(title='Limit')]
    offset: Annotated[int, Field(title='Offset')]


class FallbackRuleServiceSelection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    condition: Annotated[
        NoOutputCondition | ErrorCondition,
        Field(discriminator='type', title='Condition'),
    ]
    target: ServiceSelection


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class HttpApiConfig(BaseModel):
    """
    Configuration for HTTP API tools.
    """

    method: Annotated[Method, Field(title='Method')]
    """
    HTTP method to use for the request.
    """
    url: Annotated[str, Field(title='Url')]
    """
    Target HTTP or HTTPS URL.
    """
    headers: Annotated[dict[str, str] | None, Field(title='Headers')] = None
    """
    Static headers to include with every request.
    """
    credential_uuid: Annotated[str | None, Field(title='Credential Uuid')] = None
    """
    Reference to an external credential for request authentication.
    """
    parameters: Annotated[list[ToolParameter] | None, Field(title='Parameters')] = None
    """
    Parameters the model must provide when calling this tool.
    """
    preset_parameters: Annotated[
        list[PresetToolParameter] | None, Field(title='Preset Parameters')
    ] = None
    """
    Parameters injected by Dograh from fixed values or workflow context templates.
    """
    timeout_ms: Annotated[
        TimeoutMs | None, Field(title='Timeout Ms', validate_default=True)
    ] = 5000
    """
    Request timeout in milliseconds.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before the tool executes, while the request is in flight.
    """
    customMessageType: Annotated[
        CustomMessageType | None, Field(title='Custommessagetype')
    ] = None
    """
    Type of custom message.
    """
    customMessageRecordingId: Annotated[
        str | None, Field(title='Custommessagerecordingid')
    ] = None
    """
    Recording ID for an audio custom message.
    """
    body_template: Annotated[dict[str, Any] | None, Field(title='Body Template')] = None
    """
    Optional JSON body template for POST, PUT, and PATCH requests.
    """
    body_format: Annotated[BodyFormat | None, Field(title='Body Format')] = 'json'
    """
    Encoding of the POST, PUT, and PATCH request body: 'json' sends application/json, 'form' sends application/x-www-form-urlencoded.
    """


class HttpApiToolDefinition(BaseModel):
    """
    Tool definition for HTTP API tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['http_api'], Field(title='Type')]
    """
    Tool type.
    """
    config: HttpApiConfig
    """
    HTTP API configuration.
    """


class HttpTransferResolverConfig(BaseModel):
    """
    HTTP endpoint used to resolve transfer destination at call time.
    """

    type: Annotated[Literal['http'], Field(title='Type')] = 'http'
    """
    Resolver type.
    """
    url: Annotated[str, Field(title='Url')]
    """
    HTTP or HTTPS endpoint for transfer resolution.
    """
    headers: Annotated[dict[str, str] | None, Field(title='Headers')] = None
    """
    Static headers to include with every resolver request.
    """
    credential_uuid: Annotated[str | None, Field(title='Credential Uuid')] = None
    """
    Reference to an external credential for resolver authentication.
    """
    timeout_ms: Annotated[int | None, Field(ge=500, le=5000, title='Timeout Ms')] = 3000
    """
    Resolver request timeout in milliseconds.
    """
    wait_message: Annotated[str | None, Field(title='Wait Message')] = None
    """
    Optional short message played while Dograh resolves routing.
    """
    parameters: Annotated[list[ToolParameter] | None, Field(title='Parameters')] = None
    """
    Parameters the model may provide when calling this transfer tool.
    """
    preset_parameters: Annotated[
        list[PresetToolParameter] | None, Field(title='Preset Parameters')
    ] = None
    """
    Parameters injected by Dograh from fixed values or workflow context templates.
    """


class PropertySpec(BaseModel):
    """
    Single field on a node.

    `description` is HUMAN-FACING — shown under the field in the edit
    dialog. Keep it concise and explain what the field does.

    `llm_hint` is LLM-FACING — appears only in the `get_node_type` MCP
    response and in SDK schema output. Use it for catalog tool references
    (e.g., "Use `list_recordings`"), array shape, expected value idioms,
    or anything that would be noise in the UI. Optional; omit when the
    `description` already suffices for both audiences.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    type: PropertyType
    display_name: Annotated[str, Field(title='Display Name')]
    description: Annotated[str, Field(min_length=1, title='Description')]
    """
    Human-facing explanation shown in the UI.
    """
    llm_hint: Annotated[str | None, Field(title='Llm Hint')] = None
    """
    LLM-only guidance; omitted from the UI.
    """
    default: Annotated[Any | None, Field(title='Default')] = None
    required: Annotated[bool | None, Field(title='Required')] = False
    placeholder: Annotated[str | None, Field(title='Placeholder')] = None
    display_options: DisplayOptions | None = None
    options: Annotated[list[PropertyOption] | None, Field(title='Options')] = None
    properties: Annotated[list[PropertySpec] | None, Field(title='Properties')] = None
    min_value: Annotated[float | None, Field(title='Min Value')] = None
    max_value: Annotated[float | None, Field(title='Max Value')] = None
    min_length: Annotated[int | None, Field(title='Min Length')] = None
    max_length: Annotated[int | None, Field(title='Max Length')] = None
    pattern: Annotated[str | None, Field(title='Pattern')] = None
    editor: Annotated[str | None, Field(title='Editor')] = None
    renderer_options: PropertyRendererOptions | None = None


class RecordingListResponseSchema(BaseModel):
    """
    Response schema for list of recordings.
    """

    recordings: Annotated[list[RecordingResponseSchema], Field(title='Recordings')]
    total: Annotated[int, Field(title='Total')]


class ScheduleConfigRequest(BaseModel):
    enabled: Annotated[bool | None, Field(title='Enabled')] = True
    timezone: Annotated[str | None, Field(title='Timezone')] = 'UTC'
    slots: Annotated[
        list[TimeSlotRequest], Field(max_length=50, min_length=1, title='Slots')
    ]


class ScheduleConfigResponse(BaseModel):
    enabled: Annotated[bool, Field(title='Enabled')]
    timezone: Annotated[str, Field(title='Timezone')]
    slots: Annotated[list[TimeSlotResponse], Field(title='Slots')]


class TrafficSplitRequest(BaseModel):
    variants: Annotated[
        list[TrafficVariantRequest], Field(max_length=5, min_length=1, title='Variants')
    ]


class TrafficSplitResponse(BaseModel):
    revision: Annotated[int, Field(title='Revision')]
    variants: Annotated[list[TrafficVariantResponse], Field(title='Variants')]


class TransferCallConfig(BaseModel):
    """
    Configuration for Transfer Call tools.
    """

    introduction_enabled: Annotated[
        bool | None, Field(title='Introduction Enabled')
    ] = False
    """
    Play a generated introduction in the agent's voice to both parties before connecting them. Supported for Twilio calls with a TTS provider. Realtime speech-to-speech agents and synthesis failures skip the introduction.
    """
    introduction_prompt: Annotated[
        str | None, Field(max_length=2000, title='Introduction Prompt')
    ] = (
        "Briefly introduce this caller to the person receiving the transfer. Include"
        " their reason for calling, essential details, and any explicit language"
        " preference. Use the caller's preferred language. Keep it to one sentence, at"
        " most 25 words. Do not invent details."
    )
    """
    Instructions for the transfer introduction, including language.
    """
    destination_source: Annotated[
        DestinationSource | None, Field(title='Destination Source')
    ] = 'static'
    """
    Whether the destination is static/template, resolved by HTTP, or selected by ordered gathered/initial-context mapping rules.
    """
    destination: Annotated[str | None, Field(title='Destination')] = ''
    """
    Phone number, SIP endpoint, or template to transfer the call to, e.g. +1234567890, PJSIP/1234, or {{initial_context.transfer_destination}}.
    """
    messageType: Annotated[MessageType1 | None, Field(title='Messagetype')] = 'none'
    """
    Type of message to play before transfer.
    """
    customMessage: Annotated[str | None, Field(title='Custommessage')] = None
    """
    Custom message to play before transferring.
    """
    audioRecordingId: Annotated[str | None, Field(title='Audiorecordingid')] = None
    """
    Recording ID for audio message before transfer.
    """
    timeout: Annotated[int | None, Field(ge=5, le=120, title='Timeout')] = 30
    """
    Maximum seconds to wait for the destination to answer.
    """
    call_disposition: Annotated[
        CallDisposition | None, Field(title='Call Disposition')
    ] = None
    """
    Optional disposition to record after a successful transfer. When omitted, Dograh records its provider-specific transfer default.
    """
    parameters: Annotated[list[ToolParameter] | None, Field(title='Parameters')] = None
    """
    Parameters the model may provide when calling this transfer tool, for example state, department, or transfer reason.
    """
    resolver: HttpTransferResolverConfig | None = None
    """
    Optional resolver that determines transfer routing at call time.
    """
    context_mapping: ContextDestinationMappingConfig | None = None
    """
    Optional ordered context-to-destination routing rules.
    """


class TransferCallToolDefinition(BaseModel):
    """
    Tool definition for Transfer Call tools.
    """

    schema_version: Annotated[int | None, Field(title='Schema Version')] = 1
    """
    Schema version.
    """
    type: Annotated[Literal['transfer_call'], Field(title='Type')]
    """
    Tool type.
    """
    config: TransferCallConfig
    """
    Transfer Call configuration.
    """


class UpdateToolRequest(BaseModel):
    """
    Request schema for updating a reusable tool.
    """

    name: Annotated[Name | None, Field(title='Name')] = None
    description: Annotated[str | None, Field(title='Description')] = None
    icon: Annotated[Icon1 | None, Field(title='Icon')] = None
    icon_color: Annotated[IconColor1 | None, Field(title='Icon Color')] = None
    definition: Annotated[
        HttpApiToolDefinition
        | EndCallToolDefinition
        | TransferCallToolDefinition
        | TransferAgentToolDefinition
        | CalculatorToolDefinition
        | McpToolDefinition
        | None,
        Field(title='Definition'),
    ] = None
    status: Annotated[str | None, Field(title='Status')] = None


class ValidateWorkflowResponse(BaseModel):
    is_valid: Annotated[bool, Field(title='Is Valid')]
    errors: Annotated[list[WorkflowError], Field(title='Errors')]


class CampaignResponse(BaseModel):
    traffic_split: TrafficSplitResponse | None = None
    id: Annotated[int, Field(title='Id')]
    name: Annotated[str, Field(title='Name')]
    workflow_id: Annotated[int, Field(title='Workflow Id')]
    workflow_name: Annotated[str, Field(title='Workflow Name')]
    state: Annotated[str, Field(title='State')]
    source_type: Annotated[str, Field(title='Source Type')]
    source_id: Annotated[str, Field(title='Source Id')]
    total_rows: Annotated[int | None, Field(title='Total Rows')]
    processed_rows: Annotated[int, Field(title='Processed Rows')]
    failed_rows: Annotated[int, Field(title='Failed Rows')]
    created_at: Annotated[AwareDatetime, Field(title='Created At')]
    started_at: Annotated[AwareDatetime | None, Field(title='Started At')]
    completed_at: Annotated[AwareDatetime | None, Field(title='Completed At')]
    retry_config: RetryConfigResponse
    max_concurrency: Annotated[int | None, Field(title='Max Concurrency')] = None
    rate_limit_per_second: Annotated[
        int | None, Field(title='Rate Limit Per Second')
    ] = 1
    schedule_config: ScheduleConfigResponse | None = None
    circuit_breaker: CircuitBreakerConfigResponse | None = None
    executed_count: Annotated[int | None, Field(title='Executed Count')] = 0
    total_queued_count: Annotated[int | None, Field(title='Total Queued Count')] = 0
    parent_campaign_id: Annotated[int | None, Field(title='Parent Campaign Id')] = None
    redialed_campaign_id: Annotated[int | None, Field(title='Redialed Campaign Id')] = (
        None
    )
    telephony_configuration_id: Annotated[
        int | None, Field(title='Telephony Configuration Id')
    ] = None
    telephony_configuration_name: Annotated[
        str | None, Field(title='Telephony Configuration Name')
    ] = None
    logs: Annotated[list[CampaignLogEntryResponse] | None, Field(title='Logs')] = None
    warnings: Annotated[list[str] | None, Field(title='Warnings')] = None


class CampaignsResponse(BaseModel):
    campaigns: Annotated[list[CampaignResponse], Field(title='Campaigns')]


class CreateCampaignRequest(BaseModel):
    name: Annotated[str, Field(max_length=255, min_length=1, title='Name')]
    workflow_id: Annotated[WorkflowId | None, Field(title='Workflow Id')] = None
    traffic_split: TrafficSplitRequest | None = None
    source_type: Annotated[str, Field(pattern='^csv$', title='Source Type')]
    source_id: Annotated[str, Field(title='Source Id')]
    telephony_configuration_id: Annotated[
        int | None, Field(title='Telephony Configuration Id')
    ] = None
    retry_config: RetryConfigRequest | None = None
    max_concurrency: Annotated[
        MaxConcurrency | None, Field(title='Max Concurrency')
    ] = None
    rate_limit_per_second: Annotated[
        int | None, Field(ge=1, title='Rate Limit Per Second')
    ] = 1
    """
    Calls started per second. Defaults to 1 when omitted.
    """
    schedule_config: ScheduleConfigRequest | None = None
    circuit_breaker: CircuitBreakerConfigRequest | None = None


class CreateToolRequest(BaseModel):
    """
    Request schema for creating a reusable tool.
    """

    name: Annotated[str, Field(max_length=255, title='Name')]
    """
    Display name for the tool.
    """
    description: Annotated[str | None, Field(title='Description')] = None
    """
    Description shown to the agent when deciding whether to call it.
    """
    category: Annotated[Category | None, Field(title='Category')] = 'http_api'
    """
    Tool category. Must match definition.type.
    """
    icon: Annotated[Icon | None, Field(title='Icon', validate_default=True)] = 'globe'
    """
    Lucide icon identifier.
    """
    icon_color: Annotated[
        IconColor | None, Field(title='Icon Color', validate_default=True)
    ] = '#3B82F6'
    """
    Hex color for the tool icon.
    """
    definition: Annotated[
        HttpApiToolDefinition
        | EndCallToolDefinition
        | TransferCallToolDefinition
        | TransferAgentToolDefinition
        | CalculatorToolDefinition
        | McpToolDefinition,
        Field(discriminator='type', title='Definition'),
    ]
    """
    Typed tool definition.
    """


class FallbackPolicyServiceSelection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: Annotated[Literal[1], Field(title='Version')] = 1
    rules: Annotated[
        list[FallbackRuleServiceSelection] | None, Field(max_length=2, title='Rules')
    ] = None


class ModelConfigurationOverride(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    model_configuration_uuid: Annotated[
        UUID | None, Field(title='Model Configuration Uuid')
    ] = None
    mode: Annotated[Mode | None, Field(title='Mode')] = None
    llm: ServiceOverride | None = None
    llm_fallback: FallbackPolicyServiceSelection | None = None
    stt: ServiceOverride | None = None
    tts: ServiceOverride | None = None
    realtime: ServiceOverride | None = None
    embeddings: ServiceOverride | None = None


class NodeSpec(BaseModel):
    """
    Single source of truth for a node type.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(title='Name')]
    display_name: Annotated[str, Field(title='Display Name')]
    description: Annotated[str, Field(min_length=1, title='Description')]
    """
    Human-facing explanation shown in AddNodePanel.
    """
    llm_hint: Annotated[str | None, Field(title='Llm Hint')] = None
    """
    LLM-only guidance; omitted from the UI.
    """
    docs_url: Annotated[str | None, Field(title='Docs Url')] = None
    """
    Documentation URL shown in the node editor.
    """
    category: NodeCategory
    icon: Annotated[str, Field(title='Icon')]
    version: Annotated[str | None, Field(title='Version')] = '1.0.0'
    properties: Annotated[list[PropertySpec], Field(title='Properties')]
    examples: Annotated[list[NodeExample] | None, Field(title='Examples')] = None
    graph_constraints: GraphConstraints | None = None


class NodeTypesResponse(BaseModel):
    spec_version: Annotated[str, Field(title='Spec Version')]
    node_types: Annotated[list[NodeSpec], Field(title='Node Types')]


class WorkflowConfigurationDefaults(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    model_configuration_override: ModelConfigurationOverride | None = None
    ambient_noise_configuration: AmbientNoiseConfigurationDefaults | None = None
    max_call_duration: Annotated[
        int | None, Field(gt=0, le=1200, title='Max Call Duration')
    ] = 300
    max_user_idle_timeout: Annotated[
        float | None, Field(title='Max User Idle Timeout')
    ] = 10.0
    smart_turn_stop_secs: Annotated[
        float | None, Field(title='Smart Turn Stop Secs')
    ] = 2.0
    turn_start_strategy: Annotated[
        TurnStartStrategy | None, Field(title='Turn Start Strategy')
    ] = 'min_words'
    turn_start_min_words: Annotated[
        int | None, Field(ge=1, title='Turn Start Min Words')
    ] = 2
    turn_stop_strategy: Annotated[
        TurnStopStrategy | None, Field(title='Turn Stop Strategy')
    ] = 'transcription'
    dictionary: Annotated[str | None, Field(title='Dictionary')] = ''
    context_compaction_enabled: Annotated[
        bool | None, Field(title='Context Compaction Enabled')
    ] = False
    tts_cache_enabled: Annotated[bool | None, Field(title='Tts Cache Enabled')] = False
    """
    Reuse generated speech for repeated phrases. Supports MiniMax TTS.
    """
    call_dispositions: Annotated[
        list[CallDispositionOption] | None,
        Field(max_length=50, title='Call Dispositions'),
    ] = None
    """
    Allowed business outcomes for terminal call classification. Each entry defines the exact stored code and the criteria for selecting it.
    """
    text_chat_inactivity_timeout_seconds: Annotated[
        int | None, Field(ge=60, le=10500, title='Text Chat Inactivity Timeout Seconds')
    ] = 1800
    external_pbx_field_mappings: Annotated[
        list[ExternalPBXFieldMapping] | None,
        Field(max_length=100, title='External Pbx Field Mappings'),
    ] = None
    external_pbx_lead_headers: Annotated[
        list[ExternalPbxLeadHeader] | None,
        Field(max_length=50, title='External Pbx Lead Headers'),
    ] = None


class UpdateWorkflowRequest(BaseModel):
    name: Annotated[str | None, Field(title='Name')] = None
    workflow_definition: Annotated[
        dict[str, Any] | None, Field(title='Workflow Definition')
    ] = None
    template_context_variables: Annotated[
        dict[str, Any] | None, Field(title='Template Context Variables')
    ] = None
    workflow_configurations: WorkflowConfigurationDefaults | None = None


PropertySpec.model_rebuild()
