class FunctionNames:
    RUN_INTEGRATIONS_POST_WORKFLOW_RUN = "run_integrations_post_workflow_run"
    PROCESS_WORKFLOW_COMPLETION = "process_workflow_completion"
    SYNC_CAMPAIGN_SOURCE = "sync_campaign_source"
    PROCESS_CAMPAIGN_BATCH = "process_campaign_batch"
    PROCESS_KNOWLEDGE_BASE_DOCUMENT = "process_knowledge_base_document"
    DELIVER_WEBHOOK = "deliver_webhook"
    COMPLETE_INACTIVE_TEXT_CHAT_SESSION = "complete_inactive_text_chat_session"
    PERSIST_CALL_DATA = "persist_workflow_run_call_data"
    EXTRACT_CALL_MEMORIES = "extract_workflow_run_memories"
    REPLICATE_WORKFLOW_RUN_ARTIFACTS_S3 = "replicate_workflow_run_artifacts_s3"
    RECONCILE_PENDING_S3_REPLICATIONS = "reconcile_pending_s3_replications"
