"""Small, deterministic default CALM scorer.

Deployments can replace this function with a model-backed scorer without
changing the trend, strategy, or prompt interfaces.  Evidence is always
selected from the original utterance, never generated by the scorer.
"""

import re
from typing import Any, Mapping

DEFAULT_PARAMETERS = ("hope", "anxiety", "trust", "loneliness")

_SIGNALS: dict[str, tuple[tuple[str, ...], tuple[str, ...]]] = {
    "hope": (
        ("I don't see much point", "nothing seems", "no point", "give up", "hopeless"),
        ("better", "hopeful", "looking forward"),
    ),
    "anxiety": (
        ("panic", "worried", "scared", "can't cope", "overwhelmed"),
        ("calm", "safe", "settled"),
    ),
    "trust": (
        ("don't trust", "let down", "dismissed"),
        ("trust", "helped", "understand"),
    ),
    "loneliness": (
        ("alone", "lonely", "no one", "isolated"),
        ("connected", "together", "support"),
    ),
}


def _evidence(utterance: str, phrases: tuple[str, ...]) -> list[str]:
    found: list[str] = []
    for phrase in phrases:
        match = re.search(re.escape(phrase), utterance, flags=re.IGNORECASE)
        if match:
            found.append(utterance[match.start() : match.end()])
    return found


def score_utterance(
    utterance_verbatim: str,
    parameters: tuple[str, ...] | list[str] = DEFAULT_PARAMETERS,
) -> dict[str, dict[str, Any]]:
    """Score an utterance while preserving its exact evidence spans."""
    scores: dict[str, dict[str, Any]] = {}
    for parameter in parameters:
        high, low = _SIGNALS.get(parameter, ((), ()))
        high_evidence = _evidence(utterance_verbatim, high)
        low_evidence = _evidence(utterance_verbatim, low)
        score = max(
            0.0, min(10.0, 5.0 - 1.6 * len(high_evidence) + 0.9 * len(low_evidence))
        )
        if parameter in {"anxiety", "loneliness"}:
            score = max(
                0.0, min(10.0, 5.0 + 1.6 * len(high_evidence) - 0.9 * len(low_evidence))
            )
        evidence = high_evidence + low_evidence
        scores[parameter] = {
            "score": round(score, 2),
            "confidence": round(min(0.96, 0.62 + 0.08 * len(evidence)), 2),
            "evidence": evidence,
        }
    return scores
