import json
import re
import uuid
from datetime import datetime
from typing import Annotated, Any, Dict, List, Literal, Optional

from fastapi import APIRouter, Depends, Header, HTTPException, Query
from fastapi.responses import StreamingResponse
from httpx import HTTPStatusError
from sqlalchemy import and_, select, text
from loguru import logger
from pydantic import BaseModel, Field, ValidationError

from api.constants import DEPLOYMENT_MODE
from api.db import db_client
from api.db.agent_trigger_client import TriggerPathConflictError
from api.db.models import UserModel, WorkflowDefinitionModel, WorkflowModel
from api.db.workflow_template_client import WorkflowTemplateClient
from api.enums import (
    CallType,
    PostHogEvent,
    StorageBackend,
    WorkflowRunMode,
    WorkflowStatus,
)
from api.schemas.ai_model_configuration import OrganizationAIModelConfigurationV2
from api.schemas.copilot import (
    AgentCopilotResponse,
    CopilotChatRequest,
    InCanvasCopilotRequest,
    InCanvasCopilotResponse,
)
from api.schemas.workflow import WorkflowRunResponseSchema
from api.schemas.workflow_configurations import WorkflowConfigurationDefaults
from api.sdk_expose import sdk_expose
from api.services.auth.depends import get_superuser, get_user
from api.services.workflow.copilot_service import (
    generate_workflow_from_template_llm,
    process_copilot_turn,
    process_in_canvas_copilot_turn,
)
from api.services.configuration.ai_model_configuration import (
    WORKFLOW_MODEL_CONFIGURATION_V2_OVERRIDE_KEY,
    check_for_masked_keys_in_ai_model_configuration_v2,
    compile_ai_model_configuration_v2,
    convert_legacy_ai_model_configuration_to_v2,
    get_resolved_ai_model_configuration,
    merge_ai_model_configuration_v2_secrets,
)
from api.services.configuration.check_validity import UserConfigurationValidator
from api.services.configuration.masking import (
    mask_workflow_configurations,
    mask_workflow_definition,
    merge_workflow_api_keys,
)
from api.services.configuration.merge import merge_workflow_configuration_secrets
from api.services.configuration.resolve import (
    enrich_overrides_with_api_keys,
    resolve_effective_config,
)
from api.services.mps_service_key_client import mps_service_key_client
from api.services.posthog_client import capture_event
from api.services.reports import generate_workflow_report_csv
from api.services.storage import storage_fs
from api.services.workflow.configuration_policy import (
    ExternalPBXConfigurationDisabledError,
    WorkflowConfigurationNotFoundError,
    apply_external_pbx_mapping_policy,
)
from api.services.workflow.dto import ReactFlowDTO, sanitize_workflow_definition
from api.services.workflow.duplicate import duplicate_workflow
from api.services.workflow.errors import ItemKind, WorkflowError
from api.services.workflow.run_creation import prepare_workflow_run_inputs
from api.services.workflow.run_usage_response import (
    format_public_cost_info,
    format_public_usage_info,
)
from api.services.workflow.tool_name_validation import (
    validate_workflow_tool_name_collisions,
)
from api.services.workflow.trigger_paths import (
    TriggerPathIssue,
    ensure_trigger_paths,
    extract_trigger_paths,
    regenerate_trigger_uuids,
    trigger_path_to_node_id,
    validate_trigger_paths,
)
from api.services.workflow.workflow_graph import (
    WorkflowGraph,
    validate_node_instance_constraints,
    validate_unique_transition_tool_names,
)
from api.utils.artifacts import artifact_url
from api.utils.recording_artifacts import (
    get_recording_storage_key,
    has_recording_track,
)

router = APIRouter(prefix="/workflow")


class ValidateWorkflowResponse(BaseModel):
    is_valid: bool
    errors: list[WorkflowError]


def _trigger_conflict_http_exception(
    workflow_definition: Optional[dict], conflicting_paths: list[str]
) -> HTTPException:
    """Build a 409 with the same detail shape as validate's 422 so the editor
    can highlight the offending trigger node(s) using the same code path."""
    path_to_node = (
        trigger_path_to_node_id(workflow_definition) if workflow_definition else {}
    )
    errors: list[WorkflowError] = [
        WorkflowError(
            kind=ItemKind.node,
            id=path_to_node.get(p),
            field="data.trigger_path",
            message=(
                "Trigger path is already in use. Please choose another one "
                "or leave empty to use a unique one generated by the server."
            ),
        )
        for p in conflicting_paths
    ]
    return HTTPException(
        status_code=409,
        detail=ValidateWorkflowResponse(is_valid=False, errors=errors).model_dump(),
    )


def _trigger_path_validation_http_exception(
    issues: list[TriggerPathIssue],
) -> HTTPException:
    errors = [
        WorkflowError(
            kind=ItemKind.node,
            id=issue.node_id,
            field="data.trigger_path",
            message=issue.message,
        )
        for issue in issues
    ]
    return HTTPException(
        status_code=422,
        detail=ValidateWorkflowResponse(is_valid=False, errors=errors).model_dump(),
    )


async def _validate_workflow_definition(
    workflow_definition: Optional[dict],
    organization_id: int,
    exclude_workflow_id: Optional[int] = None,
) -> list[WorkflowError]:
    """Run DTO, graph, tool-name, and trigger checks on a workflow definition.

    Returns the list of errors (empty if the definition is valid). This is
    the single source of truth for "is this workflow valid?" — used by the
    /validate route (read-only audit) and the /publish route (gate).
    """
    errors: list[WorkflowError] = []
    if not workflow_definition:
        return errors

    # ----------- DTO Validation ------------
    dto: Optional[ReactFlowDTO] = None
    try:
        dto = ReactFlowDTO.model_validate(workflow_definition)
    except ValidationError as exc:
        errors.extend(_transform_schema_errors(exc, workflow_definition))

    # ----------- Graph Validation if DTO is valid ------------
    try:
        if dto:
            WorkflowGraph(dto)
    except ValueError as e:
        errors.extend(e.args[0])

    # ----------- Trigger Path Format Check ------------
    for issue in validate_trigger_paths(workflow_definition):
        errors.append(
            WorkflowError(
                kind=ItemKind.node,
                id=issue.node_id,
                field="data.trigger_path",
                message=issue.message,
            )
        )

    errors.extend(
        await validate_workflow_tool_name_collisions(
            workflow_definition,
            organization_id,
        )
    )

    # ----------- Trigger Path Conflict Check ------------
    trigger_paths = extract_trigger_paths(workflow_definition)
    if trigger_paths:
        conflicts = await db_client.check_trigger_path_conflicts(
            trigger_paths=trigger_paths,
            exclude_workflow_id=exclude_workflow_id,
        )
        if conflicts:
            path_to_node = trigger_path_to_node_id(workflow_definition)
            for conflicting_path in conflicts:
                errors.append(
                    WorkflowError(
                        kind=ItemKind.node,
                        id=path_to_node.get(conflicting_path),
                        field="data.trigger_path",
                        message=(
                            "Trigger path is already in use. Please choose "
                            "another one or leave empty to use a unique one "
                            "generated by the server."
                        ),
                    )
                )

    return errors


def _validation_errors_http_exception(
    errors: list[WorkflowError], status_code: int = 422
) -> HTTPException:
    """Wrap a list of validation errors in the response shape clients expect."""
    return HTTPException(
        status_code=status_code,
        detail=ValidateWorkflowResponse(is_valid=False, errors=errors).model_dump(),
    )


def _node_instance_validation_errors(
    workflow_definition: Optional[dict],
) -> list[WorkflowError]:
    """Validate spec-driven max_instances without requiring a complete draft."""
    if not workflow_definition:
        return []
    nodes = workflow_definition.get("nodes")
    if not isinstance(nodes, list):
        return []

    node_types = [
        node.get("type")
        for node in nodes
        if isinstance(node, dict) and isinstance(node.get("type"), str)
    ]
    return validate_node_instance_constraints(
        node_types,
        enforce_min_instances=False,
    )


def _transition_tool_name_validation_errors(
    workflow_definition: Optional[dict],
) -> list[WorkflowError]:
    """Validate transition names without requiring a complete draft DTO."""
    if not workflow_definition:
        return []
    edges = workflow_definition.get("edges")
    if not isinstance(edges, list):
        return []

    transitions: list[tuple[str, str, str]] = []
    for edge in edges:
        if not isinstance(edge, dict):
            continue
        edge_id = edge.get("id")
        source = edge.get("source")
        data = edge.get("data")
        label = data.get("label") if isinstance(data, dict) else None
        if (
            isinstance(edge_id, str)
            and isinstance(source, str)
            and isinstance(label, str)
            and label
        ):
            transitions.append((edge_id, source, label))

    return validate_unique_transition_tool_names(transitions)


class CallDispositionCodes(BaseModel):
    disposition_codes: list[str] = []


class WorkflowResponse(BaseModel):
    id: int
    name: str
    status: str
    created_at: datetime
    workflow_definition: dict
    current_definition_id: int | None
    template_context_variables: dict | None = None
    call_disposition_codes: CallDispositionCodes | None = None
    total_runs: int | None = None
    workflow_configurations: dict | None = None
    version_number: int | None = None
    version_status: str | None = None
    workflow_uuid: str | None = None


class WorkflowListResponse(BaseModel):
    """Lightweight response for workflow listings (excludes large fields)."""

    id: int
    name: str
    status: str
    created_at: datetime
    total_runs: int
    folder_id: int | None = None
    workflow_uuid: str | None = None


class MoveWorkflowToFolderRequest(BaseModel):
    """Move a workflow into a folder, or to "Uncategorized" when null."""

    folder_id: int | None = None


class WorkflowCountResponse(BaseModel):
    """Response for workflow count endpoint."""

    total: int
    active: int
    archived: int


class WorkflowTemplateResponse(BaseModel):
    id: int
    template_name: str
    template_description: str
    template_json: dict
    created_at: datetime


class CreateWorkflowRequest(BaseModel):
    name: str
    workflow_definition: dict


class DuplicateTemplateRequest(BaseModel):
    template_id: int
    workflow_name: str


class UpdateWorkflowRequest(BaseModel):
    name: str | None = None
    workflow_definition: dict | None = None
    template_context_variables: dict | None = None
    # Typed so field constraints (e.g. the max_call_duration cap) are
    # enforced by FastAPI; extra="allow" keeps passthrough keys like
    # model_configuration_v2_override intact.
    workflow_configurations: WorkflowConfigurationDefaults | None = None


class WorkflowVersionResponse(BaseModel):
    id: int
    version_number: int
    status: str
    created_at: datetime
    published_at: datetime | None = None
    workflow_json: dict
    workflow_configurations: dict | None = None
    template_context_variables: dict | None = None


class UpdateWorkflowStatusRequest(BaseModel):
    status: str  # "active" or "archived"


class CreateWorkflowRunRequest(BaseModel):
    mode: str
    name: str


class CreateWorkflowRunResponse(BaseModel):
    id: int
    workflow_id: int
    name: str
    mode: str
    created_at: datetime
    definition_id: int
    initial_context: dict | None = None


class CreateWorkflowTemplateRequest(BaseModel):
    call_type: Literal[CallType.INBOUND.value, CallType.OUTBOUND.value]
    use_case: str
    activity_description: str


@router.post("/{workflow_id}/validate")
async def validate_workflow(
    workflow_id: int,
    user: UserModel = Depends(get_user),
) -> ValidateWorkflowResponse:
    """
    Validate all nodes in a workflow to ensure they have required fields.

    Args:
        workflow_id: The ID of the workflow to validate
        user: The authenticated user

    Returns:
        Object indicating if workflow is valid and any invalid nodes/edges
    """
    workflow = await db_client.get_workflow(
        workflow_id, organization_id=user.selected_organization_id
    )

    if workflow is None:
        raise HTTPException(
            status_code=404, detail=f"Workflow with id {workflow_id} not found"
        )

    # Validate draft if it exists (user is editing), else validate published
    draft = await db_client.get_draft_version(workflow_id)
    workflow_definition = (
        draft.workflow_json if draft else workflow.released_definition.workflow_json
    )

    errors = await _validate_workflow_definition(
        workflow_definition,
        organization_id=user.selected_organization_id,
        exclude_workflow_id=workflow_id,
    )

    if errors:
        raise _validation_errors_http_exception(errors)

    return ValidateWorkflowResponse(is_valid=True, errors=[])


def _transform_schema_errors(
    exc: ValidationError, workflow_definition: dict
) -> list[WorkflowError]:
    out: list[WorkflowError] = []

    for err in exc.errors():
        loc = err["loc"]
        idx = workflow_definition[loc[0]][loc[1]]["id"]

        kind: ItemKind = ItemKind.node if loc[0] == "nodes" else ItemKind.edge

        out.append(
            WorkflowError(
                kind=kind,
                id=idx,
                field=".".join(str(p) for p in err["loc"][2:]) or None,
                message=err["msg"].capitalize(),
            )
        )
    return out


@router.post(
    "/create/definition",
    **sdk_expose(
        method="create_workflow",
        description="Create a new workflow from a workflow definition.",
    ),
)
async def create_workflow(
    request: CreateWorkflowRequest, user: UserModel = Depends(get_user)
) -> WorkflowResponse:
    """
    Create a new workflow from the client

    Args:
        request: The create workflow request
        user: The user to create the workflow for
    """
    # Check SaaS plan agent count limit
    from api.services.plan_service import plan_service
    can_create, err_msg = await plan_service.validate_can_create_workflow(user.selected_organization_id)
    if not can_create:
        raise HTTPException(status_code=403, detail=err_msg)

    # Auto-mint trigger_path for any trigger node that didn't ship one so
    # clients don't need to generate UUIDs themselves.
    workflow_definition = ensure_trigger_paths(request.workflow_definition)
    trigger_path_issues = validate_trigger_paths(workflow_definition)
    if trigger_path_issues:
        raise _trigger_path_validation_http_exception(trigger_path_issues)
    instance_errors = _node_instance_validation_errors(workflow_definition)
    if instance_errors:
        raise _validation_errors_http_exception(instance_errors)
    transition_errors = _transition_tool_name_validation_errors(workflow_definition)
    if transition_errors:
        raise _validation_errors_http_exception(transition_errors)
    tool_name_errors = await validate_workflow_tool_name_collisions(
        workflow_definition,
        user.selected_organization_id,
    )
    if tool_name_errors:
        raise _validation_errors_http_exception(tool_name_errors)

    # Validate trigger path uniqueness BEFORE creating the workflow so we
    # don't leave an orphaned workflow record when the trigger conflicts.
    trigger_paths = (
        extract_trigger_paths(workflow_definition) if workflow_definition else []
    )
    if trigger_paths:
        try:
            await db_client.assert_trigger_paths_available(
                trigger_paths=trigger_paths,
            )
        except TriggerPathConflictError as e:
            raise _trigger_conflict_http_exception(workflow_definition, e.trigger_paths)

    workflow = await db_client.create_workflow(
        request.name,
        workflow_definition,
        user.id,
        user.selected_organization_id,
    )

    capture_event(
        distinct_id=str(user.provider_id),
        event=PostHogEvent.WORKFLOW_CREATED,
        properties={
            "workflow_id": workflow.id,
            "workflow_name": workflow.name,
            "source": "direct",
            "organization_id": user.selected_organization_id,
        },
    )

    if trigger_paths:
        await db_client.sync_triggers_for_workflow(
            workflow_id=workflow.id,
            organization_id=user.selected_organization_id,
            trigger_paths=trigger_paths,
        )

    return {
        "id": workflow.id,
        "name": workflow.name,
        "status": workflow.status,
        "created_at": workflow.created_at,
        "workflow_definition": mask_workflow_definition(workflow_definition),
        "current_definition_id": workflow.current_definition_id,
        "template_context_variables": workflow.template_context_variables,
        "call_disposition_codes": workflow.call_disposition_codes,
        "workflow_configurations": mask_workflow_configurations(
            workflow.workflow_configurations
        ),
    }


@router.post("/copilot/chat")
async def copilot_chat(
    request: CopilotChatRequest,
    user: UserModel = Depends(get_user),
) -> AgentCopilotResponse:
    """
    Process an interactive conversational Copilot turn to construct or refine a voice agent workflow.
    """
    return await process_copilot_turn(request=request, user=user)


@router.post("/{workflow_id}/copilot/chat")
async def in_canvas_copilot_chat(
    workflow_id: int,
    request: InCanvasCopilotRequest,
    user: UserModel = Depends(get_user),
) -> InCanvasCopilotResponse:
    """
    Process an In-Canvas Copilot turn using MCP tools to directly inspect, modify, or test the workflow canvas.
    """
    return await process_in_canvas_copilot_turn(
        workflow_id=workflow_id,
        request=request,
        user=user,
    )



@router.post("/create/template")
async def create_workflow_from_template(
    request: CreateWorkflowTemplateRequest,
    user: UserModel = Depends(get_user),
) -> WorkflowResponse:
    """
    Create a new workflow from a natural language template request.

    This endpoint:
    1. Uses mps_service_key_client to call MPS workflow API
    2. Passes organization ID (authenticated mode) or created_by (OSS mode)
    3. Creates the workflow in the database

    Args:
        request: The template creation request with call_type, use_case, and activity_description
        user: The authenticated user

    Returns:
        The created workflow

    Raises:
        HTTPException: If MPS API call fails
    """
    try:
        # Check SaaS plan agent count limit
        from api.services.plan_service import plan_service
        can_create, err_msg = await plan_service.validate_can_create_workflow(user.selected_organization_id)
        if not can_create:
            raise HTTPException(status_code=403, detail=err_msg)

        # Generate workflow directly using local LLM instead of external services.dograh.com
        workflow_data = await generate_workflow_from_template_llm(
            call_type=request.call_type,
            use_case=request.use_case,
            activity_description=request.activity_description,
            user=user,
        )

        # Create the workflow in our database
        # Regenerate trigger UUIDs to avoid conflicts with existing triggers
        workflow_def = regenerate_trigger_uuids(
            workflow_data.get("workflow_definition", {})
        )

        trigger_paths = extract_trigger_paths(workflow_def) if workflow_def else []
        if trigger_paths:
            try:
                await db_client.assert_trigger_paths_available(
                    trigger_paths=trigger_paths,
                )
            except TriggerPathConflictError as e:
                raise HTTPException(status_code=409, detail=str(e))

        workflow = await db_client.create_workflow(
            name=workflow_data.get("name", f"{request.use_case} - {request.call_type}"),
            workflow_definition=workflow_def,
            user_id=user.id,
            organization_id=user.selected_organization_id,
        )

        capture_event(
            distinct_id=str(user.provider_id),
            event=PostHogEvent.WORKFLOW_CREATED,
            properties={
                "workflow_id": workflow.id,
                "workflow_name": workflow.name,
                "source": "template",
                "call_type": request.call_type,
                "use_case": request.use_case,
                "organization_id": user.selected_organization_id,
            },
        )

        if trigger_paths:
            await db_client.sync_triggers_for_workflow(
                workflow_id=workflow.id,
                organization_id=user.selected_organization_id,
                trigger_paths=trigger_paths,
            )

        return {
            "id": workflow.id,
            "name": workflow.name,
            "status": workflow.status,
            "created_at": workflow.created_at,
            "workflow_definition": mask_workflow_definition(workflow_def),
            "current_definition_id": workflow.current_definition_id,
            "template_context_variables": workflow.template_context_variables,
            "call_disposition_codes": workflow.call_disposition_codes,
            "workflow_configurations": mask_workflow_configurations(
                workflow.workflow_configurations
            ),
        }

    except HTTPException:
        raise
    except HTTPStatusError as e:
        logger.error(f"MPS API error: {e}")
        raise HTTPException(
            status_code=e.response.status_code if hasattr(e, "response") else 500,
            detail=str(e),
        )
    except Exception as e:
        logger.error(f"Unexpected error creating workflow from template: {e}")
        raise HTTPException(
            status_code=500,
            detail=f"An unexpected error occurred: {str(e)}",
        )


class WorkflowSummaryResponse(BaseModel):
    id: int
    name: str


@router.get("/count")
async def get_workflow_count(
    user: UserModel = Depends(get_user),
) -> WorkflowCountResponse:
    """Get workflow counts for the authenticated user's organization.

    This is a lightweight endpoint for checking if the user has workflows,
    useful for redirect logic without fetching full workflow data.
    """
    if not user.selected_organization_id:
        return WorkflowCountResponse(total=0, active=0, archived=0)

    counts = await db_client.get_workflow_counts(
        organization_id=user.selected_organization_id
    )

    return WorkflowCountResponse(
        total=counts["total"],
        active=counts["active"],
        archived=counts["archived"],
    )


def _validate_status_filter(status: Optional[str]) -> List[str]:
    """Parse and validate a workflow ``status`` query filter.

    Accepts a single value or a comma-separated list. Returns the list of
    validated status values (empty when no filter was supplied). Any value
    outside the ``workflow_status`` enum raises 422 so the request fails as a
    clean client error instead of a 500 from the Postgres enum cast.
    """
    if status is None or status == "":
        return []
    allowed = {s.value for s in WorkflowStatus}
    requested = [s.strip() for s in status.split(",")]
    invalid = sorted({s for s in requested if s not in allowed})
    if invalid:
        invalid_display = ["<empty>" if s == "" else s for s in invalid]
        raise HTTPException(
            status_code=422,
            detail=(
                f"Invalid workflow status filter: {invalid_display}. "
                f"Allowed values: {sorted(allowed)}."
            ),
        )
    return requested


@router.get(
    "/fetch",
    **sdk_expose(
        method="list_workflows",
        description="List all workflows in the authenticated organization.",
    ),
)
async def get_workflows(
    user: UserModel = Depends(get_user),
    status: Optional[str] = Query(
        None,
        description="Filter by status - can be single value (active/archived) or comma-separated (active,archived)",
    ),
) -> List[WorkflowListResponse]:
    """Get all workflows for the authenticated user's organization.

    Returns a lightweight response with only essential fields for listing.
    Use GET /workflow/fetch/{workflow_id} to get full workflow details.
    """
    if not user.selected_organization_id:
        return []

    statuses = _validate_status_filter(status)
    if statuses:
        # Fetch workflows for each requested status and combine the results.
        all_workflows = []
        for status_value in statuses:
            all_workflows.extend(
                await db_client.get_all_workflows_for_listing(
                    organization_id=user.selected_organization_id,
                    status=status_value,
                )
            )
        workflows = all_workflows
    else:
        # No status filter
        workflows = await db_client.get_all_workflows_for_listing(
            organization_id=user.selected_organization_id, status=None
        )

    # Get run counts for all workflows in a single query
    workflow_ids = [workflow.id for workflow in workflows]
    run_counts = await db_client.get_workflow_run_counts(workflow_ids)

    return [
        WorkflowListResponse(
            id=workflow.id,
            name=workflow.name,
            status=workflow.status,
            created_at=workflow.created_at,
            total_runs=run_counts.get(workflow.id, 0),
            folder_id=workflow.folder_id,
            workflow_uuid=workflow.workflow_uuid,
        )
        for workflow in workflows
    ]


@router.get(
    "/fetch/{workflow_id}",
    **sdk_expose(
        method="get_workflow",
        description="Get a single workflow by ID (returns draft if one exists, else published).",
    ),
)
async def get_workflow(
    workflow_id: int,
    user: UserModel = Depends(get_user),
) -> WorkflowResponse:
    """Get a single workflow by ID.

    If a draft version exists, returns the draft content for editing.
    Otherwise returns the published version's content.
    """
    workflow = await db_client.get_workflow(
        workflow_id, organization_id=user.selected_organization_id
    )
    if workflow is None:
        raise HTTPException(
            status_code=404, detail=f"Workflow with id {workflow_id} not found"
        )

    # Check for draft — editor should show draft content if it exists
    draft = await db_client.get_draft_version(workflow_id)

    if draft:
        workflow_def = draft.workflow_json
        workflow_configs = draft.workflow_configurations
        template_vars = draft.template_context_variables
    else:
        published = workflow.released_definition
        workflow_def = published.workflow_json
        workflow_configs = published.workflow_configurations
        template_vars = published.template_context_variables

    active_def = draft or workflow.released_definition
    return {
        "id": workflow.id,
        "name": workflow.name,
        "status": workflow.status,
        "created_at": workflow.created_at,
        "workflow_definition": mask_workflow_definition(workflow_def),
        "current_definition_id": workflow.current_definition_id,
        "template_context_variables": template_vars,
        "call_disposition_codes": workflow.call_disposition_codes,
        "workflow_configurations": mask_workflow_configurations(workflow_configs),
        "version_number": active_def.version_number if active_def else None,
        "version_status": active_def.status if active_def else None,
        "workflow_uuid": workflow.workflow_uuid,
    }


@router.get("/{workflow_id}/versions")
async def get_workflow_versions(
    workflow_id: int,
    limit: int | None = Query(None, ge=1, le=100),
    offset: int = Query(0, ge=0),
    user: UserModel = Depends(get_user),
) -> list[WorkflowVersionResponse]:
    """List versions for a workflow, newest first.

    Pass `limit`/`offset` to page through long histories. With no `limit`,
    returns every version (legacy behavior).
    """
    workflow = await db_client.get_workflow(
        workflow_id, organization_id=user.selected_organization_id
    )
    if workflow is None:
        raise HTTPException(
            status_code=404, detail=f"Workflow with id {workflow_id} not found"
        )

    versions = await db_client.get_workflow_versions(
        workflow_id, limit=limit, offset=offset
    )
    return [
        WorkflowVersionResponse(
            id=v.id,
            version_number=v.version_number,
            status=v.status,
            created_at=v.created_at,
            published_at=v.published_at,
            workflow_json=mask_workflow_definition(v.workflow_json),
            workflow_configurations=mask_workflow_configurations(
                v.workflow_configurations
            ),
            template_context_variables=v.template_context_variables,
        )
        for v in versions
        if v.version_number is not None
    ]


@router.post("/{workflow_id}/publish")
async def publish_workflow(
    workflow_id: int,
    user: UserModel = Depends(get_user),
):
    """Publish the current draft version of a workflow.

    Drafts are allowed to be incomplete (so the editor can save mid-edit),
    but a published version is what runtime executes — so this is the gate
    where the full DTO + graph + trigger-conflict checks must pass.
    """
    workflow = await db_client.get_workflow(
        workflow_id, organization_id=user.selected_organization_id
    )
    if workflow is None:
        raise HTTPException(
            status_code=404, detail=f"Workflow with id {workflow_id} not found"
        )

    draft = await db_client.get_draft_version(workflow_id)
    if draft is None:
        raise HTTPException(status_code=400, detail="No draft to publish")

    errors = await _validate_workflow_definition(
        draft.workflow_json,
        organization_id=user.selected_organization_id,
        exclude_workflow_id=workflow_id,
    )
    if errors:
        raise _validation_errors_http_exception(errors)

    try:
        published = await db_client.publish_workflow_draft(workflow_id)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    capture_event(
        distinct_id=str(user.provider_id),
        event=PostHogEvent.WORKFLOW_PUBLISHED,
        properties={
            "workflow_id": workflow_id,
            "version_number": published.version_number,
            "organization_id": user.selected_organization_id,
        },
    )

    return {
        "id": published.id,
        "version_number": published.version_number,
        "status": published.status,
        "published_at": published.published_at,
    }


@router.post("/{workflow_id}/create-draft")
async def create_workflow_draft(
    workflow_id: int,
    user: UserModel = Depends(get_user),
) -> WorkflowVersionResponse:
    """Create a draft version from the current published version.

    If a draft already exists, returns the existing draft.
    """
    workflow = await db_client.get_workflow(
        workflow_id, organization_id=user.selected_organization_id
    )
    if workflow is None:
        raise HTTPException(
            status_code=404, detail=f"Workflow with id {workflow_id} not found"
        )

    draft = await db_client.save_workflow_draft(workflow_id)
    return WorkflowVersionResponse(
        id=draft.id,
        version_number=draft.version_number,
        status=draft.status,
        created_at=draft.created_at,
        published_at=draft.published_at,
        workflow_json=mask_workflow_definition(draft.workflow_json),
        workflow_configurations=mask_workflow_configurations(
            draft.workflow_configurations
        ),
        template_context_variables=draft.template_context_variables,
    )


@router.get("/summary")
async def get_workflows_summary(
    user: UserModel = Depends(get_user),
    status: Optional[str] = Query(
        None,
        description="Filter by status (e.g. 'active' or 'archived'). Omit to return all.",
    ),
) -> List[WorkflowSummaryResponse]:
    """Get minimal workflow information (id and name only) for all workflows"""
    statuses = _validate_status_filter(status)
    if statuses:
        workflows = []
        for status_value in statuses:
            workflows.extend(
                await db_client.get_all_workflows(
                    organization_id=user.selected_organization_id,
                    status=status_value,
                )
            )
    else:
        workflows = await db_client.get_all_workflows(
            organization_id=user.selected_organization_id, status=None
        )
    return [
        WorkflowSummaryResponse(id=workflow.id, name=workflow.name)
        for workflow in workflows
    ]


@router.put("/{workflow_id}/status")
async def update_workflow_status(
    workflow_id: int,
    request: UpdateWorkflowStatusRequest,
    user: UserModel = Depends(get_user),
) -> WorkflowResponse:
    """
    Update the status of a workflow (e.g., archive/unarchive).

    Args:
        workflow_id: The ID of the workflow to update
        request: The status update request

    Returns:
        The updated workflow
    """
    try:
        workflow = await db_client.update_workflow_status(
            workflow_id=workflow_id,
            status=request.status,
            organization_id=user.selected_organization_id,
        )
        run_count = await db_client.get_workflow_run_count(workflow.id)
        return {
            "id": workflow.id,
            "name": workflow.name,
            "status": workflow.status,
            "created_at": workflow.created_at,
            "workflow_definition": mask_workflow_definition(
                workflow.released_definition.workflow_json
            ),
            "current_definition_id": workflow.current_definition_id,
            "template_context_variables": workflow.template_context_variables,
            "call_disposition_codes": workflow.call_disposition_codes,
            "workflow_configurations": mask_workflow_configurations(
                workflow.workflow_configurations
            ),
            "total_runs": run_count,
        }
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.put("/{workflow_id}/folder")
async def move_workflow_to_folder(
    workflow_id: int,
    request: MoveWorkflowToFolderRequest,
    user: UserModel = Depends(get_user),
) -> WorkflowListResponse:
    """Move a workflow into a folder, or to "Uncategorized" (folder_id=null).

    Validates that the target folder belongs to the caller's organization —
    the FK alone proves the folder exists, not that the caller may use it.
    """
    # Validate target folder ownership (tenant isolation) unless un-filing.
    if request.folder_id is not None:
        folder = await db_client.get_folder(
            request.folder_id, organization_id=user.selected_organization_id
        )
        if folder is None:
            raise HTTPException(
                status_code=404,
                detail=f"Folder with id {request.folder_id} not found",
            )

    try:
        workflow = await db_client.move_workflow_to_folder(
            workflow_id=workflow_id,
            folder_id=request.folder_id,
            organization_id=user.selected_organization_id,
        )
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))

    run_count = await db_client.get_workflow_run_count(workflow.id)
    return WorkflowListResponse(
        id=workflow.id,
        name=workflow.name,
        status=workflow.status,
        created_at=workflow.created_at,
        total_runs=run_count,
        folder_id=workflow.folder_id,
    )


@router.put(
    "/{workflow_id}",
    **sdk_expose(
        method="update_workflow",
        description="Update a workflow's name and/or definition. Saves as a new draft.",
    ),
)
async def update_workflow(
    workflow_id: int,
    request: UpdateWorkflowRequest,
    user: UserModel = Depends(get_user),
) -> WorkflowResponse:
    """
    Update an existing workflow.

    Args:
        workflow_id: The ID of the workflow to update
        request: The update request containing the new name and workflow definition

    Returns:
        The updated workflow

    Raises:
        HTTPException: If the workflow is not found or if there's a database error
    """
    try:
        # Strip UI runtime-only fields (invalid, validationMessage, etc.) from
        # node.data / edge.data before anything touches the DB — the UI sends
        # nodes wholesale from the React Flow store, which carries those.
        workflow_definition = sanitize_workflow_definition(request.workflow_definition)
        # Mint trigger_path for any trigger node that ships without one. The
        # response echoes workflow_definition so the client picks up the new
        # UUID without a refetch.
        workflow_definition = ensure_trigger_paths(workflow_definition)
        trigger_path_issues = validate_trigger_paths(workflow_definition)
        if trigger_path_issues:
            raise _trigger_path_validation_http_exception(trigger_path_issues)
        instance_errors = _node_instance_validation_errors(workflow_definition)
        if instance_errors:
            raise _validation_errors_http_exception(instance_errors, status_code=409)
        transition_errors = _transition_tool_name_validation_errors(workflow_definition)
        if transition_errors:
            raise _validation_errors_http_exception(transition_errors, status_code=409)
        tool_name_errors = await validate_workflow_tool_name_collisions(
            workflow_definition,
            user.selected_organization_id,
        )
        if tool_name_errors:
            raise _validation_errors_http_exception(
                tool_name_errors,
                status_code=409,
            )
        if workflow_definition:
            existing_workflow = await db_client.get_workflow(
                workflow_id, organization_id=user.selected_organization_id
            )
            if existing_workflow:
                # Merge against what the user was editing (draft or published)
                existing_draft = await db_client.get_draft_version(workflow_id)
                existing_def = (
                    existing_draft.workflow_json
                    if existing_draft
                    else existing_workflow.released_definition.workflow_json
                )
                workflow_definition = merge_workflow_api_keys(
                    workflow_definition,
                    existing_def,
                )

        # Validate model overrides. v2 uses a complete workflow-level model
        # configuration; legacy v1 uses partial service overlays.
        # exclude_unset keeps stored configs sparse: keys the request didn't
        # send stay absent so runtime defaults keep applying to them.
        workflow_configurations = (
            request.workflow_configurations.model_dump(exclude_unset=True)
            if request.workflow_configurations is not None
            else None
        )
        try:
            workflow_configurations = await apply_external_pbx_mapping_policy(
                workflow_configurations,
                workflow_id=workflow_id,
                organization_id=user.selected_organization_id,
            )
        except WorkflowConfigurationNotFoundError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        except ExternalPBXConfigurationDisabledError as exc:
            raise HTTPException(status_code=403, detail=str(exc)) from exc
        if workflow_configurations and workflow_configurations.get(
            WORKFLOW_MODEL_CONFIGURATION_V2_OVERRIDE_KEY
        ):
            existing_workflow = await db_client.get_workflow(
                workflow_id, organization_id=user.selected_organization_id
            )
            if existing_workflow is None:
                raise HTTPException(
                    status_code=404, detail=f"Workflow with id {workflow_id} not found"
                )
            existing_draft = await db_client.get_draft_version(workflow_id)
            existing_configs = (
                existing_draft.workflow_configurations
                if existing_draft
                else existing_workflow.released_definition.workflow_configurations
            )
            existing_v2_override = (existing_configs or {}).get(
                WORKFLOW_MODEL_CONFIGURATION_V2_OVERRIDE_KEY
            )
            try:
                incoming_v2_override = (
                    OrganizationAIModelConfigurationV2.model_validate(
                        workflow_configurations[
                            WORKFLOW_MODEL_CONFIGURATION_V2_OVERRIDE_KEY
                        ]
                    )
                )
                existing_v2_override_config = (
                    OrganizationAIModelConfigurationV2.model_validate(
                        existing_v2_override
                    )
                    if existing_v2_override
                    else None
                )
                v2_override = merge_ai_model_configuration_v2_secrets(
                    incoming_v2_override,
                    existing_v2_override_config,
                )
                if existing_v2_override_config is None:
                    resolved_config = await get_resolved_ai_model_configuration(
                        organization_id=user.selected_organization_id,
                    )
                    v2_override = merge_ai_model_configuration_v2_secrets(
                        v2_override,
                        resolved_config.organization_configuration,
                    )
                check_for_masked_keys_in_ai_model_configuration_v2(v2_override)
                effective = compile_ai_model_configuration_v2(v2_override)
                await UserConfigurationValidator().validate(
                    effective,
                    organization_id=user.selected_organization_id,
                    created_by=user.provider_id,
                )
            except (ValidationError, ValueError) as e:
                raise HTTPException(status_code=422, detail=str(e))
            workflow_configurations = {
                **workflow_configurations,
                WORKFLOW_MODEL_CONFIGURATION_V2_OVERRIDE_KEY: v2_override.model_dump(
                    mode="json",
                    exclude_none=True,
                ),
            }
            workflow_configurations.pop("model_overrides", None)
        elif workflow_configurations and workflow_configurations.get("model_overrides"):
            existing_workflow = await db_client.get_workflow(
                workflow_id, organization_id=user.selected_organization_id
            )
            if existing_workflow is None:
                raise HTTPException(
                    status_code=404, detail=f"Workflow with id {workflow_id} not found"
                )
            existing_draft = await db_client.get_draft_version(workflow_id)
            existing_configs = (
                existing_draft.workflow_configurations
                if existing_draft
                else existing_workflow.released_definition.workflow_configurations
            )
            workflow_configurations = merge_workflow_configuration_secrets(
                workflow_configurations,
                existing_configs,
            )
            resolved_config = await get_resolved_ai_model_configuration(
                organization_id=user.selected_organization_id,
            )
            effective_config = resolved_config.effective
            try:
                enriched_overrides = enrich_overrides_with_api_keys(
                    workflow_configurations["model_overrides"],
                    effective_config,
                )
                effective = resolve_effective_config(
                    effective_config, enriched_overrides
                )
                if resolved_config.source == "organization_v2":
                    v2_override = convert_legacy_ai_model_configuration_to_v2(effective)
                    await UserConfigurationValidator().validate(
                        compile_ai_model_configuration_v2(v2_override),
                        organization_id=user.selected_organization_id,
                        created_by=user.provider_id,
                    )
                else:
                    await UserConfigurationValidator().validate(
                        effective,
                        organization_id=user.selected_organization_id,
                        created_by=user.provider_id,
                    )
            except ValueError as e:
                raise HTTPException(status_code=422, detail=str(e))
            if resolved_config.source == "organization_v2":
                workflow_configurations = {
                    **workflow_configurations,
                    WORKFLOW_MODEL_CONFIGURATION_V2_OVERRIDE_KEY: v2_override.model_dump(
                        mode="json",
                        exclude_none=True,
                    ),
                }
                workflow_configurations.pop("model_overrides", None)
            else:
                workflow_configurations = {
                    **workflow_configurations,
                    "model_overrides": enriched_overrides,
                }

        # Reject upfront if any new trigger path collides with another
        # workflow's trigger — keeps the workflow record from
        # being updated when the trigger sync would fail.
        if workflow_definition:
            new_trigger_paths = extract_trigger_paths(workflow_definition)
            if new_trigger_paths:
                try:
                    await db_client.assert_trigger_paths_available(
                        trigger_paths=new_trigger_paths,
                        exclude_workflow_id=workflow_id,
                    )
                except TriggerPathConflictError as e:
                    raise _trigger_conflict_http_exception(
                        workflow_definition, e.trigger_paths
                    )

        workflow = await db_client.update_workflow(
            workflow_id=workflow_id,
            name=request.name,
            workflow_definition=workflow_definition,
            template_context_variables=request.template_context_variables,
            workflow_configurations=workflow_configurations,
            organization_id=user.selected_organization_id,
        )

        # Sync agent triggers if workflow definition was updated
        if workflow_definition:
            trigger_paths = extract_trigger_paths(workflow_definition)
            await db_client.sync_triggers_for_workflow(
                workflow_id=workflow.id,
                organization_id=user.selected_organization_id,
                trigger_paths=trigger_paths,
            )

        # Return draft content if one exists (save creates a draft)
        draft = await db_client.get_draft_version(workflow_id)
        if draft:
            workflow_def = draft.workflow_json
            workflow_configs = draft.workflow_configurations
            template_vars = draft.template_context_variables
        else:
            published = workflow.released_definition
            workflow_def = published.workflow_json
            workflow_configs = published.workflow_configurations
            template_vars = published.template_context_variables

        # Include version info from the active definition (draft or published)
        active_def = draft or workflow.released_definition
        return {
            "id": workflow.id,
            "name": workflow.name,
            "status": workflow.status,
            "created_at": workflow.created_at,
            "workflow_definition": mask_workflow_definition(workflow_def),
            "current_definition_id": workflow.current_definition_id,
            "template_context_variables": template_vars,
            "call_disposition_codes": workflow.call_disposition_codes,
            "workflow_configurations": mask_workflow_configurations(workflow_configs),
            "version_number": active_def.version_number if active_def else None,
            "version_status": active_def.status if active_def else None,
        }
    except HTTPException:
        raise
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/{workflow_id}/duplicate")
async def duplicate_workflow_endpoint(
    workflow_id: int,
    user: UserModel = Depends(get_user),
) -> WorkflowResponse:
    """Duplicate a workflow including its definition, configuration, recordings, and triggers."""
    try:
        # Check SaaS plan agent count limit
        from api.services.plan_service import plan_service
        can_create, err_msg = await plan_service.validate_can_create_workflow(user.selected_organization_id)
        if not can_create:
            raise HTTPException(status_code=403, detail=err_msg)

        workflow = await duplicate_workflow(
            workflow_id=workflow_id,
            organization_id=user.selected_organization_id,
            user_id=user.id,
        )

        capture_event(
            distinct_id=str(user.provider_id),
            event=PostHogEvent.WORKFLOW_DUPLICATED,
            properties={
                "workflow_id": workflow.id,
                "workflow_name": workflow.name,
                "source_workflow_id": workflow_id,
                "organization_id": user.selected_organization_id,
            },
        )

        return {
            "id": workflow.id,
            "name": workflow.name,
            "status": workflow.status,
            "created_at": workflow.created_at,
            "workflow_definition": mask_workflow_definition(
                workflow.released_definition.workflow_json
            ),
            "current_definition_id": workflow.current_definition_id,
            "template_context_variables": workflow.template_context_variables,
            "call_disposition_codes": workflow.call_disposition_codes,
            "workflow_configurations": mask_workflow_configurations(
                workflow.workflow_configurations
            ),
        }
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error(f"Error duplicating workflow {workflow_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/{workflow_id}/runs")
async def create_workflow_run(
    workflow_id: int,
    request: CreateWorkflowRunRequest,
    user: UserModel = Depends(get_user),
) -> CreateWorkflowRunResponse:
    """
    Create a new workflow run when the user decides to execute the workflow via chat or voice

    Args:
        workflow_id: The ID of the workflow to run
        request: The create workflow run request
        user: The user to create the workflow run for
    """
    workflow = await db_client.get_workflow(
        workflow_id, organization_id=user.selected_organization_id
    )
    if not workflow:
        raise HTTPException(status_code=404, detail="Workflow not found")

    run_inputs = await prepare_workflow_run_inputs(
        db_client,
        workflow,
        use_draft=True,
        include_template_context=True,
    )

    initial_context = dict(run_inputs.initial_context or {})
    call_type = CallType.OUTBOUND
    if request.mode == WorkflowRunMode.SMALLWEBRTC.value:
        configured_direction = initial_context.get("direction")
        normalized_direction = (
            configured_direction.strip().lower()
            if isinstance(configured_direction, str)
            else None
        )
        # Browser voice tests are inbound by default. A workflow author can set
        # the template-context variable `direction=outbound` to test that path.
        call_type = (
            CallType.OUTBOUND
            if normalized_direction == CallType.OUTBOUND.value
            else CallType.INBOUND
        )
        initial_context["direction"] = call_type.value

    run = await db_client.create_workflow_run(
        request.name,
        workflow_id,
        request.mode,
        user.id,
        call_type=call_type,
        organization_id=user.selected_organization_id,
        definition_id=run_inputs.definition_id,
        use_draft=run_inputs.use_draft,
        initial_context=initial_context,
    )
    return {
        "id": run.id,
        "workflow_id": run.workflow_id,
        "name": run.name,
        "mode": run.mode,
        "created_at": run.created_at,
        "definition_id": run.definition_id,
        "initial_context": run.initial_context,
        "gathered_context": run.gathered_context,
    }


@router.get("/{workflow_id}/runs/{run_id}")
async def get_workflow_run(
    workflow_id: int, run_id: int, user: UserModel = Depends(get_user)
) -> WorkflowRunResponseSchema:
    run = await db_client.get_workflow_run(
        run_id, organization_id=user.selected_organization_id
    )
    if not run:
        raise HTTPException(status_code=404, detail="Workflow run not found")

    public_access_token = run.public_access_token
    user_recording_url = get_recording_storage_key(run.extra, "user")
    bot_recording_url = get_recording_storage_key(run.extra, "bot")
    has_user_recording = has_recording_track(run.extra, "user")
    has_bot_recording = has_recording_track(run.extra, "bot")
    if (
        run.transcript_url
        or run.recording_url
        or has_user_recording
        or has_bot_recording
    ) and not public_access_token:
        public_access_token = await db_client.ensure_public_access_token(run.id)

    return {
        "id": run.id,
        "workflow_id": run.workflow_id,
        "name": run.name,
        "mode": run.mode,
        "is_completed": run.is_completed,
        "transcript_url": run.transcript_url,
        "recording_url": run.recording_url,
        "user_recording_url": user_recording_url,
        "bot_recording_url": bot_recording_url,
        "transcript_public_url": artifact_url(public_access_token, "transcript"),
        "recording_public_url": artifact_url(public_access_token, "recording"),
        "user_recording_public_url": (
            artifact_url(public_access_token, "user_recording")
            if has_user_recording
            else None
        ),
        "bot_recording_public_url": (
            artifact_url(public_access_token, "bot_recording")
            if has_bot_recording
            else None
        ),
        "public_access_token": public_access_token,
        "cost_info": format_public_cost_info(run.cost_info, run.usage_info),
        "usage_info": format_public_usage_info(run.usage_info),
        "created_at": run.created_at,
        "definition_id": run.definition_id,
        "initial_context": run.initial_context,
        "gathered_context": run.gathered_context,
        "call_type": run.call_type,
        "logs": run.logs,
        "annotations": run.annotations,
    }


class WorkflowRunsResponse(BaseModel):
    runs: List[WorkflowRunResponseSchema]
    total_count: int
    page: int
    limit: int
    total_pages: int
    applied_filters: Optional[List[dict]] = None


@router.get("/{workflow_id}/runs")
async def get_workflow_runs(
    workflow_id: int,
    page: int = Query(1, ge=1, description="Page number (starts from 1)"),
    limit: int = Query(50, ge=1, le=100, description="Number of items per page"),
    filters: Optional[str] = Query(None, description="JSON-encoded filter criteria"),
    sort_by: Optional[str] = Query(
        None, description="Field to sort by (e.g., 'duration', 'created_at')"
    ),
    sort_order: Optional[str] = Query(
        "desc", description="Sort order ('asc' or 'desc')"
    ),
    user: UserModel = Depends(get_user),
) -> WorkflowRunsResponse:
    """
    Get workflow runs with optional filtering and sorting.

    Filters should be provided as a JSON-encoded array of filter criteria.
    Example: [{"attribute": "dateRange", "value": {"from": "2024-01-01", "to": "2024-01-31"}}]
    """
    offset = (page - 1) * limit

    # Parse filters if provided
    filter_criteria = []
    if filters:
        try:
            filter_criteria = json.loads(filters)
        except json.JSONDecodeError:
            raise HTTPException(status_code=400, detail="Invalid filter format")

        # Restrict allowed filter attributes for regular users
        allowed_attributes = {
            "dateRange",
            "dispositionCode",
            "duration",
            "status",
            "tokenUsage",
        }
        for filter_item in filter_criteria:
            attribute = filter_item.get("attribute")
            if attribute and attribute not in allowed_attributes:
                raise HTTPException(
                    status_code=403, detail=f"Invalid attribute '{attribute}'"
                )

    runs, total_count = await db_client.get_workflow_runs_by_workflow_id(
        workflow_id,
        organization_id=user.selected_organization_id,
        limit=limit,
        offset=offset,
        filters=filter_criteria if filter_criteria else None,
        sort_by=sort_by,
        sort_order=sort_order,
    )

    total_pages = (total_count + limit - 1) // limit

    return WorkflowRunsResponse(
        runs=runs,
        total_count=total_count,
        page=page,
        limit=limit,
        total_pages=total_pages,
        applied_filters=filter_criteria if filter_criteria else None,
    )


@router.get("/{workflow_id}/report")
async def download_workflow_report(
    workflow_id: int,
    user: UserModel = Depends(get_user),
    start_date: Optional[datetime] = Query(
        None, description="Filter runs created on or after this datetime (ISO 8601)"
    ),
    end_date: Optional[datetime] = Query(
        None, description="Filter runs created on or before this datetime (ISO 8601)"
    ),
) -> StreamingResponse:
    """Download a CSV report of completed runs for a workflow."""
    workflow = await db_client.get_workflow(
        workflow_id, organization_id=user.selected_organization_id
    )
    if workflow is None:
        raise HTTPException(
            status_code=404, detail=f"Workflow with id {workflow_id} not found"
        )

    output, filename = await generate_workflow_report_csv(
        workflow_id, start_date=start_date, end_date=end_date
    )

    return StreamingResponse(
        output,
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/templates")
async def get_workflow_templates() -> List[WorkflowTemplateResponse]:
    """
    Get all available workflow templates.

    Returns:
        List of workflow templates
    """
    template_client = WorkflowTemplateClient()
    templates = await template_client.get_all_workflow_templates()

    return [
        {
            "id": template.id,
            "template_name": template.template_name,
            "template_description": template.template_description,
            "template_json": template.template_json,
            "created_at": template.created_at,
        }
        for template in templates
    ]


@router.post("/templates/duplicate")
async def duplicate_workflow_template(
    request: DuplicateTemplateRequest, user: UserModel = Depends(get_user)
) -> WorkflowResponse:
    """
    Duplicate a workflow template to create a new workflow for the user.

    Args:
        request: The duplicate template request
        user: The authenticated user

    Returns:
        The newly created workflow
    """
    template_client = WorkflowTemplateClient()
    template = await template_client.get_workflow_template(request.template_id)

    if not template:
        raise HTTPException(
            status_code=404,
            detail=f"Workflow template with id {request.template_id} not found",
        )

    # Create a new workflow from the template
    # Regenerate trigger UUIDs to avoid conflicts with existing triggers
    workflow_def = regenerate_trigger_uuids(template.template_json)

    trigger_paths = extract_trigger_paths(workflow_def) if workflow_def else []
    if trigger_paths:
        try:
            await db_client.assert_trigger_paths_available(
                trigger_paths=trigger_paths,
            )
        except TriggerPathConflictError as e:
            raise HTTPException(status_code=409, detail=str(e))

    workflow = await db_client.create_workflow(
        request.workflow_name,
        workflow_def,
        user.id,
        user.selected_organization_id,
    )

    if trigger_paths:
        await db_client.sync_triggers_for_workflow(
            workflow_id=workflow.id,
            organization_id=user.selected_organization_id,
            trigger_paths=trigger_paths,
        )

    return {
        "id": workflow.id,
        "name": workflow.name,
        "status": workflow.status,
        "created_at": workflow.created_at,
        "workflow_definition": mask_workflow_definition(workflow_def),
        "current_definition_id": workflow.current_definition_id,
        "template_context_variables": workflow.template_context_variables,
        "call_disposition_codes": workflow.call_disposition_codes,
        "workflow_configurations": mask_workflow_configurations(
            workflow.workflow_configurations
        ),
    }


# ---------------------------------------------------------------------------
# Ambient Noise Upload
# ---------------------------------------------------------------------------


class AmbientNoiseUploadRequest(BaseModel):
    workflow_id: int
    filename: str
    mime_type: str = "audio/wav"
    file_size: int = Field(..., gt=0, le=10_485_760, description="Max 10MB")


class AmbientNoiseUploadResponse(BaseModel):
    upload_url: str
    storage_key: str
    storage_backend: str


@router.post(
    "/ambient-noise/upload-url",
    response_model=AmbientNoiseUploadResponse,
    summary="Get a presigned URL to upload a custom ambient noise audio file",
)
async def get_ambient_noise_upload_url(
    request: AmbientNoiseUploadRequest,
    user=Depends(get_user),
):
    """Generate a presigned PUT URL for uploading a custom ambient noise file."""
    # Verify user owns this workflow
    workflow = await db_client.get_workflow(
        request.workflow_id, organization_id=user.selected_organization_id
    )
    if not workflow:
        raise HTTPException(status_code=404, detail="Workflow not found")

    sanitized = re.sub(r"[^a-zA-Z0-9._-]", "_", request.filename)
    storage_key = (
        f"ambient-noise/{user.selected_organization_id}"
        f"/{request.workflow_id}/{uuid.uuid4()}_{sanitized}"
    )

    upload_url = await storage_fs.aget_presigned_put_url(
        file_path=storage_key,
        expiration=1800,
        content_type=request.mime_type,
        max_size=request.file_size,
    )
    if not upload_url:
        raise HTTPException(status_code=500, detail="Failed to generate upload URL")

    return AmbientNoiseUploadResponse(
        upload_url=upload_url,
        storage_key=storage_key,
        storage_backend=StorageBackend.get_current_backend().value,
    )


# ---------------------------------------------------------------------------
# Platform Built-in Agents (Templates) Management
# ---------------------------------------------------------------------------

WORKFLOW_BUILTIN_MIGRATION_STATEMENTS = [
    "ALTER TABLE workflows ADD COLUMN IF NOT EXISTS is_builtin BOOLEAN DEFAULT FALSE",
    "ALTER TABLE workflows ADD COLUMN IF NOT EXISTS builtin_category VARCHAR(64) DEFAULT 'Sales'",
    "ALTER TABLE workflows ADD COLUMN IF NOT EXISTS builtin_badge VARCHAR(64) DEFAULT 'Featured'",
    "ALTER TABLE workflows ADD COLUMN IF NOT EXISTS builtin_description TEXT DEFAULT ''",
    "ALTER TABLE workflows ADD COLUMN IF NOT EXISTS builtin_variables JSONB DEFAULT '[]'::jsonb",
    "ALTER TABLE workflows ADD COLUMN IF NOT EXISTS builtin_conversion_goal JSONB DEFAULT '{}'::jsonb",
    "ALTER TABLE workflows ADD COLUMN IF NOT EXISTS tested_by_admin BOOLEAN DEFAULT FALSE",
    "ALTER TABLE workflows ADD COLUMN IF NOT EXISTS tested_at TIMESTAMPTZ",
]

_MIGRATIONS_APPLIED = False


async def _ensure_builtin_columns():
    global _MIGRATIONS_APPLIED
    if _MIGRATIONS_APPLIED:
        return
    try:
        async with db_client.async_session() as session:
            for sql in WORKFLOW_BUILTIN_MIGRATION_STATEMENTS:
                try:
                    await session.execute(text(sql))
                except Exception as ex:
                    logger.debug(f"Workflow builtin column migration note: {ex}")
            await session.commit()
            _MIGRATIONS_APPLIED = True
    except Exception as e:
        logger.warning(f"Could not execute builtin workflow column migrations: {e}")


class PublishBuiltinAgentRequest(BaseModel):
    category: str = "Sales"
    badge: str = "Featured"
    description: str = ""
    variables: list[dict] = []
    conversion_goal: dict = {}
    confirm_tested: bool = True


class CreateBuiltinAgentRequest(BaseModel):
    name: str
    description: Optional[str] = ""
    category: Optional[str] = "Sales & Outreach"
    badge: Optional[str] = "Official Template"
    first_message: Optional[str] = ""
    system_prompt: Optional[str] = ""
    language: Optional[str] = "en-IN"
    voice_id: Optional[str] = "default"
    variables: list[dict] = []
    conversion_goal: dict = {}


class ImportBuiltinAgentRequest(BaseModel):
    name: Optional[str] = None


def _format_agent_item(w: WorkflowModel) -> dict:
    definition = w.workflow_definition or {}
    if isinstance(definition, str):
        try:
            definition = json.loads(definition)
        except Exception:
            definition = {}
    nodes = definition.get("nodes", []) if isinstance(definition, dict) else []
    agent_data = {}
    for n in nodes:
        if isinstance(n, dict) and n.get("type") in ("agent", "startCall", "agentNode"):
            d = n.get("data", {})
            if isinstance(d, dict):
                agent_data = {
                    **d,
                    "first_message": d.get("first_message") or d.get("greeting") or "",
                    "system_prompt": d.get("system_prompt") or d.get("prompt") or "",
                }
            break

    raw_vars = w.builtin_variables or []
    if isinstance(raw_vars, str):
        try:
            raw_vars = json.loads(raw_vars)
        except Exception:
            raw_vars = []
    formatted_vars = []
    existing_keys = set()
    if isinstance(raw_vars, list):
        for v in raw_vars:
            if isinstance(v, dict):
                k = v.get("key") or v.get("name") or ""
                if k:
                    existing_keys.add(k)
                    formatted_vars.append({
                        "name": v.get("name") or k,
                        "key": k,
                        "label": v.get("label") or k.replace("_", " ").title(),
                        "type": v.get("type", "text"),
                        "placeholder": v.get("placeholder") or v.get("defaultValue") or "",
                    })
            elif isinstance(v, str) and v:
                existing_keys.add(v)
                formatted_vars.append({
                    "name": v,
                    "key": v,
                    "label": v.replace("_", " ").title(),
                    "type": "text",
                    "placeholder": "",
                })

    # Auto-discover any {{variable}} inside system_prompt and first_message if not already listed
    prompt_text = f"{agent_data.get('system_prompt', '')} {agent_data.get('first_message', '')}"
    for k in re.findall(r"\{\{([a-zA-Z0-9_]+)\}\}", prompt_text):
        if k not in existing_keys:
            existing_keys.add(k)
            formatted_vars.append({
                "name": k,
                "key": k,
                "label": k.replace("_", " ").title(),
                "type": "text",
                "placeholder": f"Enter {k.replace('_', ' ')}",
            })

    goal = w.builtin_conversion_goal or {}
    if isinstance(goal, str):
        try:
            goal = json.loads(goal)
        except Exception:
            goal = {"goal": goal}

    return {
        "id": w.id,
        "workflow_uuid": w.workflow_uuid,
        "name": w.name,
        "category": w.builtin_category or "Sales",
        "badge": w.builtin_badge or "Featured",
        "description": w.builtin_description or "",
        "is_default": bool(w.is_builtin),
        "variables": formatted_vars,
        "conversion_goal": goal,
        "tested_by_admin": bool(w.tested_by_admin),
        "tested_at": w.tested_at.isoformat() if w.tested_at else None,
        "call_type": agent_data.get("call_type", "outbound"),
        "language": agent_data.get("language", "en-IN"),
        "voice_id": agent_data.get("voice", "default"),
        "first_message": agent_data.get("first_message", ""),
        "system_prompt": agent_data.get("system_prompt", ""),
    }


@router.get("/builtin")
async def get_builtin_agents_catalog(
    limit: Optional[int] = Query(50),
):
    """
    Fetch all platform built-in AI callers created by administrators.
    Only returns agents where is_builtin == True and status is ACTIVE.
    """
    await _ensure_builtin_columns()
    async with db_client.async_session() as session:
        stmt = (
            select(WorkflowModel)
            .where(
                and_(
                    WorkflowModel.is_builtin == True,
                    WorkflowModel.status == WorkflowStatus.ACTIVE.value,
                )
            )
            .order_by(WorkflowModel.id.desc())
        )
        res = await session.execute(stmt)
        workflows = res.scalars().all()
        return [_format_agent_item(w) for w in workflows[:limit]]


@router.get("")
@router.get("/")
async def get_builtin_agents(
    is_default: Optional[bool] = Query(None),
    limit: Optional[int] = Query(50),
    authorization: Annotated[str | None, Header()] = None,
    x_api_key: Annotated[str | None, Header(alias="X-API-Key")] = None,
):
    """
    Fetch all platform built-in agents (templates) or user workflows.
    Publicly accessible for default agents (marketing landing page).
    If authenticated and is_default is not True, also includes user's workflows.
    """
    await _ensure_builtin_columns()
    async with db_client.async_session() as session:
        user = None
        if authorization or x_api_key:
            try:
                user = await get_user(authorization=authorization, x_api_key=x_api_key)
            except Exception:
                pass

        results = []
        if user and user.selected_organization_id and is_default is not True:
            org_workflows = await db_client.get_all_workflows_for_listing(
                organization_id=user.selected_organization_id, status=None
            )
            for w in org_workflows[:limit]:
                results.append(_format_agent_item(w))

        if is_default or not results:
            stmt = (
                select(WorkflowModel)
                .where(
                    and_(
                        WorkflowModel.is_builtin == True,
                        WorkflowModel.status == WorkflowStatus.ACTIVE.value,
                    )
                )
                .order_by(WorkflowModel.id.desc())
            )
            res = await session.execute(stmt)
            workflows = res.scalars().all()

            for w in workflows[:limit]:
                if not any(r["id"] == w.id for r in results):
                    results.append(_format_agent_item(w))

        return results


@router.post("/{workflow_id}/mark-tested")
async def mark_agent_tested(
    workflow_id: int,
    user: UserModel = Depends(get_user),
):
    """Mark an agent as tested by admin or creator."""
    await _ensure_builtin_columns()
    async with db_client.async_session() as session:
        stmt = select(WorkflowModel).where(WorkflowModel.id == workflow_id)
        res = await session.execute(stmt)
        workflow = res.scalar_one_or_none()
        if not workflow:
            raise HTTPException(status_code=404, detail="Agent not found")

        # Verify access
        if not user.is_superuser and workflow.organization_id != user.selected_organization_id:
            raise HTTPException(status_code=403, detail="Permission denied")

        workflow.tested_by_admin = True
        workflow.tested_at = datetime.now()
        await session.commit()
        return {"status": "success", "workflow_id": workflow_id, "tested": True}


@router.post("/{workflow_id}/publish-builtin")
async def publish_builtin_agent(
    workflow_id: int,
    request: PublishBuiltinAgentRequest,
    user: UserModel = Depends(get_superuser),
):
    """
    Publish an agent as a platform built-in agent (Superuser only).
    Enforces that the agent has been tested before being added to platform catalog.
    """
    await _ensure_builtin_columns()
    async with db_client.async_session() as session:
        stmt = select(WorkflowModel).where(WorkflowModel.id == workflow_id)
        res = await session.execute(stmt)
        workflow = res.scalar_one_or_none()
        if not workflow:
            raise HTTPException(status_code=404, detail="Agent not found")

        # Verify test requirement
        if not workflow.tested_by_admin and not request.confirm_tested:
            raise HTTPException(
                status_code=400,
                detail="Admin must test the agent before publishing it as a platform built-in agent.",
            )

        workflow.is_builtin = True
        workflow.status = WorkflowStatus.ACTIVE.value
        workflow.builtin_category = request.category or "Sales & Outreach"
        workflow.builtin_badge = request.badge or "Official Template"
        workflow.builtin_description = request.description or ""
        workflow.builtin_variables = request.variables or []
        workflow.builtin_conversion_goal = request.conversion_goal or {}
        workflow.tested_by_admin = True
        if not workflow.tested_at:
            workflow.tested_at = datetime.now()

        # Ensure released definition exists and is current
        if not workflow.released_definition_id:
            def_stmt = (
                select(WorkflowDefinitionModel)
                .where(WorkflowDefinitionModel.workflow_id == workflow.id)
                .order_by(WorkflowDefinitionModel.id.desc())
            )
            def_res = await session.execute(def_stmt)
            existing_def = def_res.scalars().first()
            if existing_def:
                workflow.released_definition_id = existing_def.id
                existing_def.is_current = True
                existing_def.status = "published"
                if not existing_def.published_at:
                    existing_def.published_at = datetime.now()
            else:
                wf_def_row = WorkflowDefinitionModel(
                    workflow_id=workflow.id,
                    workflow_json=workflow.workflow_definition or {},
                    is_current=True,
                    status="published",
                    version_number=1,
                    published_at=datetime.now(),
                    workflow_configurations=workflow.workflow_configurations or {},
                    template_context_variables=workflow.template_context_variables or {},
                )
                session.add(wf_def_row)
                await session.flush()
                workflow.released_definition_id = wf_def_row.id

        wf_name = workflow.name
        wf_id = workflow.id
        wf_cat = workflow.builtin_category

        await session.commit()
        return {
            "status": "success",
            "message": f"Agent '{wf_name}' published as platform built-in template.",
            "workflow_id": wf_id,
            "category": wf_cat,
        }


@router.delete("/{workflow_id}/unpublish-builtin")
async def unpublish_builtin_agent(
    workflow_id: int,
    user: UserModel = Depends(get_superuser),
):
    """Unpublish an agent from the platform built-in catalog (Superuser only)."""
    await _ensure_builtin_columns()
    async with db_client.async_session() as session:
        stmt = select(WorkflowModel).where(WorkflowModel.id == workflow_id)
        res = await session.execute(stmt)
        workflow = res.scalar_one_or_none()
        if not workflow:
            raise HTTPException(status_code=404, detail="Agent not found")

        wf_name = workflow.name
        workflow.is_builtin = False
        await session.commit()
        return {"status": "success", "message": f"Agent '{wf_name}' unpublished from built-in catalog."}


@router.post("/builtin")
@router.post("/builtin/create")
async def create_builtin_agent(
    request: CreateBuiltinAgentRequest,
    user: UserModel = Depends(get_superuser),
):
    """
    Directly create and publish a new platform built-in AI caller agent (Superuser only).
    """
    await _ensure_builtin_columns()
    async with db_client.async_session() as session:
        prompt = request.system_prompt or "You are a professional voice AI assistant. Speak politely and help the caller."
        greeting = request.first_message or ""
        nodes = [
            {
                "id": "start_1",
                "type": "startCall",
                "position": {"x": 250, "y": 150},
                "data": {
                    "name": request.name.strip(),
                    "prompt": prompt,
                    "greeting": greeting if greeting else None,
                    "greeting_type": "text" if greeting else None,
                    "allow_interrupt": True,
                    "is_start": True,
                    "wait_for_user_response": False if greeting else True,
                    "first_message": greeting,
                    "system_prompt": prompt,
                    "language": request.language or "en-IN",
                    "voice": request.voice_id or "default",
                    "call_type": "outbound",
                },
            }
        ]
        definition = {"nodes": nodes, "edges": []}

        new_workflow = WorkflowModel(
            name=request.name.strip(),
            workflow_uuid=str(uuid.uuid4()),
            user_id=user.id,
            organization_id=user.selected_organization_id or 1,
            status=WorkflowStatus.ACTIVE.value,
            workflow_definition=definition,
            is_builtin=True,
            builtin_category=request.category or "Sales & Outreach",
            builtin_badge=request.badge or "Official Template",
            builtin_description=request.description or "",
            builtin_variables=request.variables or [],
            builtin_conversion_goal=request.conversion_goal or {},
            tested_by_admin=True,
            tested_at=datetime.now(),
        )
        session.add(new_workflow)
        await session.flush()

        wf_def_row = WorkflowDefinitionModel(
            workflow_id=new_workflow.id,
            workflow_json=definition,
            is_current=True,
            status="published",
            version_number=1,
            published_at=datetime.now(),
            workflow_configurations={},
            template_context_variables={},
        )
        session.add(wf_def_row)
        await session.flush()
        new_workflow.released_definition_id = wf_def_row.id

        formatted_result = _format_agent_item(new_workflow)
        await session.commit()
        return formatted_result


@router.delete("/builtin/{workflow_id}")
async def delete_builtin_agent(
    workflow_id: int,
    user: UserModel = Depends(get_superuser),
):
    """Permanently delete a built-in agent from the platform catalog (Superuser only)."""
    async with db_client.async_session() as session:
        wf = await session.get(WorkflowModel, workflow_id)
        if not wf:
            raise HTTPException(status_code=404, detail="Agent not found")
        await session.delete(wf)
        await session.commit()
        return {"status": "success", "message": f"Agent #{workflow_id} deleted"}


@router.post("/builtin/{workflow_id}/import")
async def import_builtin_agent(
    workflow_id: int,
    request: ImportBuiltinAgentRequest,
    user: UserModel = Depends(get_user),
):
    """
    Import/clone a platform built-in agent into the calling user's account.
    Creates an independent private copy owned by the user's organization.
    """
    await _ensure_builtin_columns()
    async with db_client.async_session() as session:
        stmt = select(WorkflowModel).where(
            and_(
                WorkflowModel.id == workflow_id,
                WorkflowModel.is_builtin == True,
            )
        )
        res = await session.execute(stmt)
        source = res.scalar_one_or_none()
        if not source:
            raise HTTPException(status_code=404, detail="Built-in agent not found")

        import copy

        source_name = source.name
        cloned_definition = copy.deepcopy(source.workflow_definition or {})
        for node in cloned_definition.get("nodes", []):
            if node.get("type") == "trigger":
                node.setdefault("data", {})["trigger_path"] = str(uuid.uuid4())

        new_name = request.name or f"{source_name} (My Copy)"
        new_workflow = WorkflowModel(
            name=new_name,
            workflow_uuid=str(uuid.uuid4()),
            user_id=user.id,
            organization_id=user.selected_organization_id,
            status=WorkflowStatus.ACTIVE.value,
            workflow_definition=cloned_definition,
            template_context_variables=copy.deepcopy(source.template_context_variables or {}),
            call_disposition_codes=copy.deepcopy(source.call_disposition_codes or {}),
            workflow_configurations=copy.deepcopy(source.workflow_configurations or {}),
            is_builtin=False,
        )
        session.add(new_workflow)
        await session.flush()

        new_def = WorkflowDefinitionModel(
            workflow_id=new_workflow.id,
            workflow_json=cloned_definition,
            template_context_variables=copy.deepcopy(source.template_context_variables or {}),
            workflow_configurations=copy.deepcopy(source.workflow_configurations or {}),
            is_current=True,
            status="published",
            version_number=1,
            published_at=datetime.now(),
        )
        session.add(new_def)
        await session.flush()
        new_workflow.released_definition_id = new_def.id
        new_id = new_workflow.id

        await session.commit()

        return {
            "status": "success",
            "message": f"Successfully imported '{source_name}' into your agents!",
            "workflow_id": new_id,
            "name": new_name,
        }


async def _seed_default_builtin_workflows(session):
    """Seed initial rich built-in agents into DB if catalog is empty."""
    default_templates = [
        {
            "name": "Real Estate Lead Qualification",
            "category": "Real Estate",
            "badge": "Most Popular",
            "description": "Connects with property inquiry leads, checks budget, preferred city, and schedules site tours.",
            "first_message": "Hello! Main {{company_name}} se baat kar rahi hoon regarding your recent property inquiry for {{project_name}}. Do you have 2 minutes to discuss?",
            "system_prompt": "Aap {{company_name}} ke courteous aur sharp property advisor hain. Aapka mission prospect se respectful and warm conversation karke unka requirement qualify karna hai: 1. Puraani inquiry confirm karein for {{project_name}} in {{preferred_city}}. 2. Unse unka budget range puchhein. 3. 2 BHK ya 3 BHK requirement check karein. 4. Free VIP site visit book karein.",
            "variables": [
                {"key": "company_name", "label": "Company Name", "defaultValue": "Apex Realty"},
                {"key": "project_name", "label": "Project Name", "defaultValue": "Skyline Residency"},
                {"key": "preferred_city", "label": "City / Location", "defaultValue": "Gurgaon"},
            ],
            "conversion_goal": {
                "type": "appointment_booked",
                "label": "Site Visit / Tour Scheduled",
                "conditionPrompt": "Customer agreed to schedule a property site visit or confirmed high intent to buy.",
            },
        },
        {
            "name": "Doctor Consultation Booking",
            "category": "Healthcare",
            "badge": "Verified",
            "description": "Confirms patient consultations, handles slot adjustments, and records clinic visit intent.",
            "first_message": "Namaste! Main {{clinic_name}} se bol rahi hoon regarding your appointment with {{doctor_name}}. Kya aap scheduled time par aa rahe hain?",
            "system_prompt": "Aap {{clinic_name}} ke patient coordinator hain. 1. Patient ki appointment confirm karein with {{doctor_name}}. 2. Agar reschedule karna chahein toh alternate morning/evening slot offer karein. 3. Past prescriptions laane ka reminder dein.",
            "variables": [
                {"key": "clinic_name", "label": "Clinic Name", "defaultValue": "City Care Clinic"},
                {"key": "doctor_name", "label": "Doctor Name", "defaultValue": "Dr. Sharma"},
            ],
            "conversion_goal": {
                "type": "appointment_booked",
                "label": "Consultation Confirmed",
                "conditionPrompt": "Patient confirmed their consultation attendance or confirmed rescheduled slot.",
            },
        },
        {
            "name": "E-Commerce COD Confirmation",
            "category": "E-Commerce",
            "badge": "High ROI",
            "description": "Verifies Cash on Delivery orders before shipping to reduce expensive courier RTO returns.",
            "first_message": "Namaste! Main {{store_name}} dispatch team se bol raha hoon to confirm your Cash on Delivery order for {{item_name}}. Kya aapka delivery address confirm karein?",
            "system_prompt": "Aap {{store_name}} ke dispatch security officer hain. 1. Customer se unka order confirm karein for {{item_name}}. 2. Delivery address aur pincode verify karein. 3. Cash ready rakhne ki request karein. 4. Cancellation chahein toh politely accept karein.",
            "variables": [
                {"key": "store_name", "label": "Store Name", "defaultValue": "SwiftStore"},
                {"key": "item_name", "label": "Ordered Product", "defaultValue": "Wireless Earbuds"},
            ],
            "conversion_goal": {
                "type": "interest_confirmed",
                "label": "Order Verified for Dispatch",
                "conditionPrompt": "Customer confirmed order details, delivery address, and verified cash payment readiness.",
            },
        },
        {
            "name": "Payment & EMI Follow-up",
            "category": "Finance",
            "badge": "Compliant",
            "description": "Polite and compliant automated reminder for overdue invoices or loan installments.",
            "first_message": "Hello! Main {{company_name}} accounts desk se call kar raha hoon regarding your upcoming installment due date. Have you already processed the payment?",
            "system_prompt": "Aap {{company_name}} ke respectful finance accounts officer hain. 1. Due date politely remind karein. 2. Agar payment ho gaya hai toh note karein. 3. Pending hai toh WhatsApp par instant payment link lene ka offer karein.",
            "variables": [
                {"key": "company_name", "label": "Company / Lender", "defaultValue": "Apex Capital"},
            ],
            "conversion_goal": {
                "type": "payment_promised",
                "label": "Payment Date Confirmed",
                "conditionPrompt": "Customer confirmed date of payment or agreed to receive instant UPI payment link.",
            },
        },
    ]

    for tmpl in default_templates:
        wf_def = {
            "nodes": [
                {
                    "id": "start_1",
                    "type": "startCall",
                    "data": {
                        "name": tmpl["name"],
                        "prompt": tmpl["system_prompt"],
                        "greeting": tmpl["first_message"],
                        "greeting_type": "text",
                        "allow_interrupt": True,
                        "is_start": True,
                        "wait_for_user_response": False,
                        "first_message": tmpl["first_message"],
                        "system_prompt": tmpl["system_prompt"],
                        "language": "en-IN",
                        "voice": "default",
                        "model": "gpt-4.1-mini",
                        "call_type": "outbound",
                    },
                    "position": {"x": 200, "y": 100},
                },
            ],
            "edges": [],
        }

        wf = WorkflowModel(
            name=tmpl["name"],
            workflow_uuid=str(uuid.uuid4()),
            status=WorkflowStatus.ACTIVE.value,
            workflow_definition=wf_def,
            is_builtin=True,
            builtin_category=tmpl["category"],
            builtin_badge=tmpl["badge"],
            builtin_description=tmpl["description"],
            builtin_variables=tmpl["variables"],
            builtin_conversion_goal=tmpl["conversion_goal"],
            tested_by_admin=True,
            tested_at=datetime.now(),
        )
        session.add(wf)
        await session.flush()

        wf_def_row = WorkflowDefinitionModel(
            workflow_id=wf.id,
            workflow_json=wf_def,
            is_current=True,
            status="published",
            version_number=1,
            published_at=datetime.now(),
        )
        session.add(wf_def_row)
        await session.flush()
        wf.released_definition_id = wf_def_row.id

    await session.commit()

