name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Config files location
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          # Use PAT to trigger deployment workflow
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}